-- //////////////////////////////////////////////////////////////
-- // DATA BASE:		DATA_02
-- // MODULE:			ARCUSFIL
-- // OPERATION:		TABLA
-- //////////////////////////////////////////////////////////////
-- // AUTHOR:			AX
-- // CREATION DATE:	20210118
-- ////////////////////////////////////////////////////////////// 

--USE [DATA_02Pruebas]
GO

-- //////////////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////////////
-- // DROPs
-- //////////////////////////////////////////////////////////////
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ARCUSFIL_SQL]') AND type in (N'U'))
	DROP TABLE [dbo].[ARCUSFIL_SQL]
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ARCUSFIL_CONTACT]') AND type in (N'U'))
	DROP TABLE [dbo].[ARCUSFIL_CONTACT]
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ARCUSFIL_ADDRESS]') AND type in (N'U'))
	DROP TABLE [dbo].[ARCUSFIL_ADDRESS]
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ADDRESS_TYPE]') AND type in (N'U'))
	DROP TABLE [dbo].[ADDRESS_TYPE]
GO


-- ////////////////////////////////////////////////////////////////
-- //					ADDRESS_TYPE				 
-- ////////////////////////////////////////////////////////////////

CREATE TABLE [dbo].[ADDRESS_TYPE] (
	[K_ADDRESS_TYPE]				[INT]			NOT NULL,
	[D_ADDRESS_TYPE]				[VARCHAR](100)	NOT NULL,
	[C_ADDRESS_TYPE]				[VARCHAR](255)	NOT NULL,
	[S_ADDRESS_TYPE]				[VARCHAR](10)	NOT NULL,
	[O_ADDRESS_TYPE]				[INT]			NOT NULL,
	[L_ADDRESS_TYPE]				[INT]			NOT NULL
) ON [PRIMARY]
GO
-- //////////////////////////////////////////////////////
ALTER TABLE [dbo].[ADDRESS_TYPE]
	ADD CONSTRAINT [PK_ADDRESS_TYPE]
		PRIMARY KEY CLUSTERED ([K_ADDRESS_TYPE])
GO
CREATE UNIQUE NONCLUSTERED 
	INDEX [UN_ADDRESS_TYPE_01_DESCRIPCION] 
	   ON [dbo].[ADDRESS_TYPE] ( [D_ADDRESS_TYPE] )
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_CI_ADDRESS_TYPE]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_CI_ADDRESS_TYPE]
GO
-- //////////////////////////////////////////////////////////////
-- //				CI - ADDRESS_TYPE
-- //////////////////////////////////////////////////////////////
CREATE PROCEDURE [dbo].[PG_CI_ADDRESS_TYPE]
	@PP_K_SISTEMA_EXE					INT,
	@PP_K_USUARIO_ACCION				INT,
	-- ===========================
	@PP_K_ADDRESS_TYPE			INT,
	@PP_D_ADDRESS_TYPE			VARCHAR(100),
	@PP_C_ADDRESS_TYPE			VARCHAR(255),
	@PP_S_ADDRESS_TYPE			VARCHAR(10),
	@PP_O_ADDRESS_TYPE			INT,
	@PP_L_ADDRESS_TYPE			INT
AS
	-- ===========================
	INSERT INTO ADDRESS_TYPE
			(	[K_ADDRESS_TYPE], [D_ADDRESS_TYPE], 
				[C_ADDRESS_TYPE], [S_ADDRESS_TYPE], 
				[O_ADDRESS_TYPE], [L_ADDRESS_TYPE]		)
	VALUES	
			(	@PP_K_ADDRESS_TYPE, @PP_D_ADDRESS_TYPE, 
				@PP_C_ADDRESS_TYPE, @PP_S_ADDRESS_TYPE,
				@PP_O_ADDRESS_TYPE, @PP_L_ADDRESS_TYPE	)		
	-- //////////////////////////////////////////////////////////////
GO

EXECUTE [dbo].[PG_CI_ADDRESS_TYPE]  0, 139,  01, 'BILL TO'				,'' , 'BILL-TO', 10 , 1
EXECUTE [dbo].[PG_CI_ADDRESS_TYPE]  0, 139,  02, 'SHIP TO'				,'' , 'SHIP-TO', 20 , 1
--EXECUTE [dbo].[PG_CI_ADDRESS_TYPE]  0, 139,  03, 'DELIVERY TO'			,'' , 'DLIVTO', 30 , 1
GO

-- ////////////////////////////////////////////////////////////////
-- //					ARCUSFIL_ADDRESS				 
-- ////////////////////////////////////////////////////////////////

CREATE TABLE [dbo].[ARCUSFIL_ADDRESS] (
	[A4GLIdentity_ADDRESS]		[INT] IDENTITY (1,1)	NOT NULL,
	[A4GLIdentity]				[INT]			NOT NULL,
	[K_ADDRESS_TYPE]			[INT]			NOT NULL,
	-- ============================
	[D_ARCUSFIL_ADDRESS_NAME]	[VARCHAR](300)	NOT NULL,							-- NAME
	[D_ARCUSFIL_ADDRESS_01]		[VARCHAR](300)	NOT NULL DEFAULT '',				-- ADDRESS 01
	[D_ARCUSFIL_ADDRESS_02]		[VARCHAR](300)	NOT NULL DEFAULT '',				-- ADDRESS 02
	[D_ARCUSFIL_ADDRESS_03]		[VARCHAR](300)	NOT NULL DEFAULT '',				-- ADDRESS 03
	[D_ARCUSFIL_ADDRESS_04]		[VARCHAR](300)	NOT NULL DEFAULT '',				-- COUNTRY
	-- ============================
	[L_ARCUSFIL_ADDRESS_MAIN]	[INT]			NOT NULL DEFAULT 0
) ON [PRIMARY]
GO
-- //////////////////////////////////////////////////////
ALTER TABLE [dbo].[ARCUSFIL_ADDRESS]
	ADD CONSTRAINT [PA4GLIdentity_ADDRESS]
		PRIMARY KEY CLUSTERED ([A4GLIdentity_ADDRESS])
GO
-- //////////////////////////////////////////////////////

ALTER TABLE [dbo].[ARCUSFIL_ADDRESS] 
	ADD		[K_USUARIO_ALTA]			[INT] NOT NULL,
			[F_ALTA]					[DATETIME] NOT NULL,
			[K_USUARIO_CAMBIO]			[INT] NOT NULL,
			[F_CAMBIO]					[DATETIME] NOT NULL,
			[L_BORRADO]					[INT] NOT NULL,
			[K_USUARIO_BAJA]			[INT] NULL,
			[F_BAJA]					[DATETIME] NULL;
GO


-- ////////////////////////////////////////////////////////////////
-- //					ARCUSFIL_CONTACT				 
-- ////////////////////////////////////////////////////////////////
CREATE TABLE [dbo].[ARCUSFIL_CONTACT] (
	[A4GLIdentity_CONTACT]		[INT] IDENTITY (1,1)	NOT NULL,
	[A4GLIdentity]								[INT]			NOT NULL,		
	[D_ARCUSFIL_CONTACT_NAME]					[VARCHAR](255)	NOT NULL,
	-- ============================
	[ARCUSFIL_CONTACT_PHONE_01]					[VARCHAR](25)	NULL DEFAULT '',
	[ARCUSFIL_CONTACT_PHONE_01_EXT]				[VARCHAR](25)	NULL DEFAULT 0,
	[ARCUSFIL_CONTACT_EMAIL_01]					[VARCHAR](150)	NULL DEFAULT '',
	[ARCUSFIL_CONTACT_FAX_01]					[VARCHAR](25)	NULL DEFAULT '',
	-- ============================
	[C_ARCUSFIL_CONTACT]						[VARCHAR](500)	NOT NULL DEFAULT ''
) ON [PRIMARY]
GO
-- //////////////////////////////////////////////////////
ALTER TABLE [dbo].[ARCUSFIL_CONTACT]
	ADD CONSTRAINT [PA4GLIdentity_CONTACT]
		PRIMARY KEY CLUSTERED ([A4GLIdentity_CONTACT])
GO
-- //////////////////////////////////////////////////////
ALTER TABLE [dbo].[ARCUSFIL_CONTACT] 
	ADD		[K_USUARIO_ALTA]			[INT] NOT NULL,
			[F_ALTA]					[DATETIME] NOT NULL,
			[K_USUARIO_CAMBIO]			[INT] NOT NULL,
			[F_CAMBIO]					[DATETIME] NOT NULL,
			[L_BORRADO]					[INT] NOT NULL,
			[K_USUARIO_BAJA]			[INT] NULL,
			[F_BAJA]					[DATETIME] NULL;
GO


-- ////////////////////////////////////////////////////////////////
-- //					ARCUSFIL				 
-- ////////////////////////////////////////////////////////////////
--CREATE TABLE [dbo].[ARCUSFIL] (
--	[A4GLIdentity]						[INT]			NOT NULL,
--	[D_ARCUSFIL]						[VARCHAR](500)	NOT NULL,
--	[C_ARCUSFIL]						[VARCHAR](500)	NOT NULL,
--	[S_ARCUSFIL]						[VARCHAR](10)	NOT NULL,
--	-- ============================
--	[K_CONTINENTE]						[INT]			NOT NULL,
--	[K_COUNTRY]							[INT]			NOT NULL,
--	[K_STATE_GEO]						[INT]			NOT NULL,
--	[ARCUSFIL_CITY]						[VARCHAR](100)	NULL DEFAULT '', 
--	[D_ARCUSFIL_ADDRESS_MAIN_01]		[VARCHAR](500)	NOT NULL,				-- STREET
--	[D_ARCUSFIL_ADDRESS_MAIN_02]		[VARCHAR](500)	NOT NULL DEFAULT '',	-- COLONY, FRACC,
--	[ARCUSFIL_POSTAL_CODE]				[VARCHAR](15)	NULL DEFAULT 0,
--	-- ============================	
--	[F_ARCUSFIL_DATE]					[DATE]			NOT NULL,
--	[O_ARCUSFIL]						[INT]			NOT NULL,
--	[L_ARCUSFIL]						[INT]			NOT NULL,
--	[ARCUSFIL_EMAIL_MAIN]				[VARCHAR](150)	NULL DEFAULT ''
--) ON [PRIMARY]
--GO
---- //////////////////////////////////////////////////////
--ALTER TABLE [dbo].[ARCUSFIL]
--	ADD CONSTRAINT [PA4GLIdentity]
--		PRIMARY KEY CLUSTERED ([A4GLIdentity])
--GO
--CREATE UNIQUE NONCLUSTERED 
--	INDEX [UN_ARCUSFIL_01_DESCRIPCION] 
--	   ON [dbo].[ARCUSFIL] ( [S_ARCUSFIL] )
--GO


-- //////////////////////////////////////////////////////
--	EQUIVALENCIAS ENTRE TABLAS
--		CUS_NO			=	S_CUSTOMXER
--		CUS_NAME		=	D_CUSTOMXER

-- ////////////////////////////////////////////////////////////////
-- //					ARCUSFIL				 
-- ////////////////////////////////////////////////////////////////
CREATE TABLE [dbo].[ARCUSFIL_SQL]	(
			-- ============================	
			-- CAMPOS ORIGINALES DE LA TABLA INTEGRADOS
			[A4GLIdentity]						[INT] IDENTITY (1,1)	NOT NULL,
			[CUS_NO]							[VARCHAR]	(12),
			[CUS_NAME]							[VARCHAR]	(150),
			-- ============================	
			[K_CONTINENTE]						[INT]			NOT NULL,
			[K_COUNTRY]							[INT]			NOT NULL,
			[K_STATE_GEO]						[INT]			NOT NULL,
			[ARCUSFIL_CITY]						[VARCHAR](100)	NULL DEFAULT '', 
			[D_ARCUSFIL_ADDRESS_MAIN_01]		[VARCHAR](500)	NOT NULL,				-- STREET
			[D_ARCUSFIL_ADDRESS_MAIN_02]		[VARCHAR](500)	NOT NULL DEFAULT '',	-- COLONY, FRACC,
			[ARCUSFIL_POSTAL_CODE]				[VARCHAR](15)	NULL DEFAULT 0,
			-- ============================	
			[F_ARCUSFIL_DATE]					[DATE]			NOT NULL,
			[O_ARCUSFIL]						[INT]			NOT NULL,
			[L_ARCUSFIL]						[INT]			NOT NULL,
			[ARCUSFIL_EMAIL_MAIN]				[VARCHAR](150)	NULL DEFAULT '',
			-- ===========================
			[C_ARCUSFIL]						[VARCHAR](500)	NOT NULL,
			-- ===========================
			--	CAMPOS QUE SE VERIFICARAN SI SE PUEDEN ELIMINAR
			[SLSPSN_NO]							[VARCHAR]	(3)	NOT NULL DEFAULT '2',
			[CUST_TYPE_CD]						[VARCHAR]	(5) NOT NULL DEFAULT 'MCUEX',
			[COLLECTOR]							[VARCHAR]	(3) NOT NULL DEFAULT '',
			[CURR_CD]							[VARCHAR]	(3) NOT NULL DEFAULT 'USD',
			[CMT_2]								[VARCHAR]	(30) NOT NULL DEFAULT '',
			[CMT_1]								[VARCHAR]	(30) NOT NULL DEFAULT '',
			[HOLD_FG]							[VARCHAR]	(1)	 NOT NULL DEFAULT 'N'
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ARCUSFIL_SQL]
ADD
			[K_USUARIO_ALTA]					[INT] NOT NULL,
			[F_ALTA]							[DATETIME] NOT NULL,
			[K_USUARIO_CAMBIO]					[INT] NOT NULL,
			[F_CAMBIO]							[DATETIME] NOT NULL,
			[L_BORRADO]							[INT] NOT NULL,
			[K_USUARIO_BAJA]					[INT] NULL,
			[F_BAJA]							[DATETIME] NULL;
GO

-- //////////////////////////////////////////////////////
ALTER TABLE [dbo].[ARCUSFIL_SQL]	
	ADD CONSTRAINT [PA4GLIdentity]
		PRIMARY KEY CLUSTERED ([A4GLIdentity])
GO
CREATE UNIQUE NONCLUSTERED 
	INDEX [UN_ARCUSFIL_SQL_01_DESCRIPCION] 
	   ON [dbo].[ARCUSFIL_SQL]	( [CUS_NO] )
GO


--	ALTER TABLE [dbo].[ARCUSFIL_SQL]									-- AX - 20210122
--	ALTER COLUMN	[USER_DEF_FLD_2]		[INT] NOT NULL DEFAULT 0
--	GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_CI_ARCUSFIL_SQL]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_CI_ARCUSFIL_SQL]
GO

-- //////////////////////////////////////////////////////////////
-- //				CI - ARCUSFIL
-- //////////////////////////////////////////////////////////////

CREATE PROCEDURE [dbo].[PG_CI_ARCUSFIL_SQL]
	@PP_K_SISTEMA_EXE					INT,
	@PP_K_USUARIO_ACCION				INT,
	-- ===========================
--	@PP_A4GLIdentity				INT,
	@PP_D_ARCUSFIL				VARCHAR(500),
	@PP_C_ARCUSFIL				VARCHAR(500),
	@PP_S_ARCUSFIL				VARCHAR(10),
	-- ============================
	@PP_K_CONTINENTE			INT,
	@PP_K_COUNTRY				INT,
	@PP_K_STATE_GEO				INT,
	@PP_ARCUSFIL_CITY			VARCHAR(100),
	@PP_D_ARCUSFIL_ADDRESS_01	VARCHAR(500),
	@PP_D_ARCUSFIL_ADDRESS_02	VARCHAR(500),
	@PP_ARCUSFIL_POSTAL_CODE	VARCHAR(15),
	-- ============================
	@PP_F_ARCUSFIL_DATE			DATE,
	@PP_O_ARCUSFIL				INT,
	@PP_L_ARCUSFIL				INT,
	@PP_ARCUSFIL_EMAIL_MAIN		VARCHAR(150),
	-- ============================
	@PP_SLSPSN_NO						[VARCHAR]	(3)	,
	@PP_CUST_TYPE_CD					[VARCHAR]	(5) ,
	@PP_COLLECTOR						[VARCHAR]	(3) ,
	@PP_CURR_CD							[VARCHAR]	(3) ,
	@PP_CMT_2							[VARCHAR]	(30),
	@PP_CMT_1							[VARCHAR]	(30),
	@PP_HOLD_FG							[VARCHAR]	(1)	
AS				
	-- ===========================
	INSERT INTO [dbo].[ARCUSFIL_SQL]
			(	--[A4GLIdentity],		
				[CUS_NAME], 
				[C_ARCUSFIL],		[CUS_NO], 
				-- ===========================
				[K_CONTINENTE],
				[K_COUNTRY],		[K_STATE_GEO],				
				[ARCUSFIL_CITY],	
				[D_ARCUSFIL_ADDRESS_MAIN_01],	
				[D_ARCUSFIL_ADDRESS_MAIN_02],
				[ARCUSFIL_POSTAL_CODE],		[F_ARCUSFIL_DATE],			
				[O_ARCUSFIL],				[L_ARCUSFIL],
				-- ===========================
				[ARCUSFIL_EMAIL_MAIN],
				[SLSPSN_NO]			,
				[CUST_TYPE_CD]		,
				[COLLECTOR]			,
				[CURR_CD]			,
				[CMT_2]				,
				[CMT_1]				,
				[HOLD_FG]			,
				-- ===========================
				[K_USUARIO_ALTA], [F_ALTA], [K_USUARIO_CAMBIO], [F_CAMBIO],
				[L_BORRADO], [K_USUARIO_BAJA], [F_BAJA]  )
	VALUES	
			(	--@PP_A4GLIdentity,		
				@PP_D_ARCUSFIL, 
				@PP_C_ARCUSFIL,		@PP_S_ARCUSFIL,
				@PP_K_CONTINENTE,
				@PP_K_COUNTRY,		@PP_K_STATE_GEO,
				@PP_ARCUSFIL_CITY,			
				@PP_D_ARCUSFIL_ADDRESS_01,	@PP_D_ARCUSFIL_ADDRESS_02,
				@PP_ARCUSFIL_POSTAL_CODE,	@PP_F_ARCUSFIL_DATE,
				-- ===========================
				@PP_O_ARCUSFIL, @PP_L_ARCUSFIL,
				@PP_ARCUSFIL_EMAIL_MAIN,
				@PP_SLSPSN_NO						,
				@PP_CUST_TYPE_CD					,
				@PP_COLLECTOR						,
				@PP_CURR_CD							,
				@PP_CMT_2							,
				@PP_CMT_1							,
				@PP_HOLD_FG							,
				-- ===========================
				@PP_K_USUARIO_ACCION, GETDATE(), @PP_K_USUARIO_ACCION, GETDATE(),
				0, NULL, NULL  )
GO	
	
EXECUTE [dbo].[PG_CI_ARCUSFIL_SQL] 0, 139,'CNI INC', 'CNI INC' , 'CNII01' , 200,221 , 54, 'TROY', '1148 ROCHESTER ROAD' ,'' , '48083' , '1998-05-22' , '1' , '1','','2','MCUEX','','USD','FOB ACUNA','N/A','N'
EXECUTE [dbo].[PG_CI_ARCUSFIL_SQL] 0, 139,'EBINGER BROTHERS LEATHER COMPANY', 'EBINGER BROTHERS LEATHER COMPANY' , 'EBIN01' , 200,221 , 53, 'MASSACHUSETTS', '44 MITCHELL ROAD' ,'IPSWICH' , '1938' , '2001-02-12' , '2' , '1','','2','MSUEX','','USD','','N/A','N'
EXECUTE [dbo].[PG_CI_ARCUSFIL_SQL] 0, 139,'ENSAMBLE DE INTERIORES AUTOMOTRICES', 'ENSAMBLE DE INTERIORES AUTOMOTRICES' , 'ENSA01' , 200,260 , 8, 'CD JUAREZ, CHIH.', 'BLVD. OSCAR FLORES 4250' ,'' , '32650' , '2001-06-07' , '3' , '1','','2','MISC ','','USD','','N/A','N'
EXECUTE [dbo].[PG_CI_ARCUSFIL_SQL] 0, 139,'FINDLAY INDUSTRIES*********', 'FINDLAY INDUSTRIES*************' , 'FIND01' , 200,221 , 67, 'OHIO', '4000 FOSTORIA ROAD' ,'FINDLAY 0410 45840' , '45840' , '1998-05-22' , '4' , '1','','2','MCUEX','','USD','NETT CIF','N/A','N'
EXECUTE [dbo].[PG_CI_ARCUSFIL_SQL] 0, 139,'FINDLAY INDUSTRIES (FLORIDA)***********', 'FINDLAY INDUSTRIES (FLORIDA)************' , 'FIND02' , 200,221 , 41, 'FLORIDA', 'PO BOX 1350' ,'LAKE WALES' , '33853' , '1999-09-02' , '5' , '1','','2','MCUEX','','USD','NETT CIF','N/A','N'
EXECUTE [dbo].[PG_CI_ARCUSFIL_SQL] 0, 139,'GLOBALTEX 2000 LTD', 'GLOBALTEX 2000 LTD' , 'GLOB01' , 200,213 , 0, '', 'UNIT C/735 PRINCE ROAD' ,'WINDSOR' , 'N9C2Z2' , '2000-03-23' , '6' , '1','','2','MCUEX','','USD','','N/A','N'
EXECUTE [dbo].[PG_CI_ARCUSFIL_SQL] 0, 139,'IRVIN AUTOMOTIVE PRODUCTS -PONTIAC', 'IRVIN AUTOMOTIVE' , 'IRVI02' , 200,221 , 54, 'PONTIAC', '2600 CENTER POINT PARKWAY' ,'' , '48341' , '2001-07-25' , '7' , '1','','2','MFUEX','','USD','','N/A','N'
EXECUTE [dbo].[PG_CI_ARCUSFIL_SQL] 0, 139,'AUTOSEAT S.A. DE C.V.', 'AUTOSEAT S.A. DE C.V.' , 'JITC01' , 200,260 , 15, 'NAUCALPA', 'PLANT#18232' ,'CALLE NEGRA MODELO #6A FRACC ALCE BLANCO' , '53370' , '1999-11-11' , '8' , '1','','2','MCUEX','','USD','','N/A','N'
EXECUTE [dbo].[PG_CI_ARCUSFIL_SQL] 0, 139,'Johnson Control Interiors LLC', 'JOHNSON CONTROL INTERIORS LLC' , 'JOHN02' , 200,221 , 75, 'El Paso', '1320 Goodyear Dr' ,'' , '79936' , '2001-03-04' , '9' , '1','','2','MCUEX','','USD','','N/A','N'
EXECUTE [dbo].[PG_CI_ARCUSFIL_SQL] 0, 139, 'KRAFT AUTOMOTIVE GROUP, INC', 'KRAFT AUTOMOTIVE GROUP, INC' , 'KRAF01' , 200,221 , 54, 'HOWELL', '955 GRAND OAKS DRIVE' ,'' , '48843' , '2001-04-26' , '10' , '1','','8','MFUEX','','USD','','N/A','N'
EXECUTE [dbo].[PG_CI_ARCUSFIL_SQL] 0, 139, 'LEAR NAB CORPORATION (FAVESA)', 'LEAR NAB CORPORATION (FAVESA)' , 'LEAR05' , 200,221 , 75, 'EL PASO', '1440 DON HASKINS' ,'' , '79936' , '1998-05-25' , '11' , '1','','2','MCUEX','','USD','','N/A','N'
EXECUTE [dbo].[PG_CI_ARCUSFIL_SQL] 0, 139, 'LEAR TECHNOLOGIES, LLC', 'LEAR TECHNOLOGIES, LLC' , 'LEAT01' , 200,221 , 79, '', 'PO BOX 4178' ,'SOUTHFIELD' , '48086-4178' , '2000-03-09' , '12' , '1','','2','MFUEX','','USD','','N/A','N'
EXECUTE [dbo].[PG_CI_ARCUSFIL_SQL] 0, 139, 'LEAR MEXICAN SEATING CORP', 'LEAR RIO BRAVO' , 'LEAV01' , 200,221 , 75, 'EL PASO', '9500 PLAZA CIRCLE' ,'P.O. BOX 17709' , '79917-7709' , '1999-02-25' , '13' , '1','','2','MFUEX','','USD','','N/A','N'
EXECUTE [dbo].[PG_CI_ARCUSFIL_SQL] 0, 139, 'Leatherworks LLC', 'LEATHERWORKS LLC' , 'LEAW01' , 200,221 , 54, 'ALLEN PARK', 'ATTN Accounts Payable' ,'16630 Southfield Road, Suite 3100' , '48101' , '2001-08-22' , '14' , '1','','2','MFUEX','','USD','','Duty Paid','N'
EXECUTE [dbo].[PG_CI_ARCUSFIL_SQL] 0, 139, 'LEAR CORPORATION - GM DIVISION', 'LEAR CORPORATION - GM DIVISION' , 'LEGM01' , 200,221 , 54, 'WARREN', '5800 ENTERPRISE DRIVE' ,'' , '48092' , '1999-11-19' , '15' , '1','','2','MFUEX','','USD','','N/A','N'
EXECUTE [dbo].[PG_CI_ARCUSFIL_SQL] 0, 139, 'LEAR CORP FORD DIVISION', 'LEAR CORP FORD DIVISION' , 'LFOR01' , 200,221 , 54, 'DEARBORN', '5250 AUTO CLUB DRIVE ANNEX' ,'' , '48126' , '1999-04-30' , '16' , '1','','2','MFUEX','','USD','','N/A','N'
EXECUTE [dbo].[PG_CI_ARCUSFIL_SQL] 0, 139, 'SEATING SYSTEMS OF SABINAS', 'SEATING SYSTEMS OF SABINAS' , 'MAGN01' , 200,221 , 75, 'EAGLE PASS', 'A DIV OF Magna Seating of America, Inc.' ,'540 SOUTH BIBB PMB #1' , '78852' , '1999-11-12' , '17' , '1','','2','MCUEX','','USD','','N/A','N'
EXECUTE [dbo].[PG_CI_ARCUSFIL_SQL] 0, 139, 'MAGNA SEATING OF AMERICA INC (ACUÑA)', 'MAGNA SEATING OF AMERICA' , 'MAGN02' , 200,221 , 75, 'DEL RIO', '2199 SPUR 239' ,'MAILING TO: P.O BOX 420699' , '78840' , '2000-02-01' , '18' , '1','','2','MCUEX','','USD','','N/A','N'
EXECUTE [dbo].[PG_CI_ARCUSFIL_SQL] 0, 139, 'SEATING SYS.OF ACUNA DIV INTIER AUTO', 'MAGNA SEATING SYSTEMS OF ACUNA' , 'MAGN03' , 200,221 , 75, 'DEL RIO', '2199 SPUR 239' ,'P.O. BOX 420699' , '78840' , '2000-07-28' , '19' , '1','','2','MCUEX','','USD','','N/A','N'
EXECUTE [dbo].[PG_CI_ARCUSFIL_SQL] 0, 139, 'MAZDA CANADA INC', 'MAZDA CANADA INC' , 'MAZC01' , 200,213 , 83, 'SCARBOROUGH', '305 MILNER AVENUE,' ,'SUITE 400' , 'MIB 3V4' , '2000-03-22' , '20' , '1','','2','MFUEX','','USD','','N/A','N'
EXECUTE [dbo].[PG_CI_ARCUSFIL_SQL] 0, 139, 'MAZDA NORTH AMERICAN OPERATION', 'MAZDA NORTH AMERICAN OPERATION' , 'MAZN01' , 200,221 , 37, 'IRVINE', '7755 IRVINE CENTRE DRIVE' ,'' , '92618-2922' , '2000-03-22' , '21' , '1','','2','MFUEX','','USD','','N/A','N'
EXECUTE [dbo].[PG_CI_ARCUSFIL_SQL] 0, 139, 'MCDONALD EXP-DO NOT USE', 'MCDONALD EXPORTS -DO NOT USE' , 'MCDO01' , 500,501 , 105, 'SOUTHPORT', 'SUITE 1 SOUTHPORT CHASE' ,'19 EXPO COURT' , '4215' , '2001-08-03' , '22' , '1','','2','MISC ','','USD','','ABN','N'
EXECUTE [dbo].[PG_CI_ARCUSFIL_SQL] 0, 139, 'MCDONALD EXPORTS (AUST) P/L', 'MCDONALD EXPORTS (AUST) P/L' , 'MCDO02' , 500,501 , 105, 'SOUTHPORT', 'SUITE 1 SOUTHPORT CHASE' ,'19 EXPO COURT' , '4215' , '2001-08-03' , '23' , '1','','2','MISC ','','USD','','ABN','N'
EXECUTE [dbo].[PG_CI_ARCUSFIL_SQL] 0, 139, 'MEXICAN INDUSTRIES**DO NOT USE**', 'MEXICAN INDUSTRIES**DO NOT USE**' , 'MEXI02' , 200,221 , 54, 'DETROIT', 'ATT : PATTY ODELL' ,'1801 HOWARD STREET' , '48216' , '1998-11-30' , '24' , '1','','2','MCUEX','','USD','','N/A','Y'
EXECUTE [dbo].[PG_CI_ARCUSFIL_SQL] 0, 139, 'MORIDEN AMERICA, INC.', 'MORIDEN' , 'MORI01' , 200,221 , 46, 'INDIANAPOLIS', '915 WESTERN DRIVE' ,'' , '46241' , '1998-07-01' , '25' , '1','','2','MCUEX','','USD','','N/A','N'
EXECUTE [dbo].[PG_CI_ARCUSFIL_SQL] 0, 139, '1004274 ONTARIO LTD', 'ONTARIO LTD' , 'ONTA01' , 200,213 , 83, 'ONTARIO', '993 BUCKSKIN WAY' ,'ORLEANS' , '2Y7' , '2000-06-22' , '26' , '1','','8','MSUEX','','USD','L/C','N/A','N'
EXECUTE [dbo].[PG_CI_ARCUSFIL_SQL] 0, 139, 'TECHNOTRIM', 'TECHNOTRIM' , 'TECH01' , 200,221 , 54, 'CANTON', '42015 FORD ROAD BOX 358' ,'' , '48187-3669' , '2000-01-31' , '27' , '1','','2','MCUEX','','USD','','N/A','N'
EXECUTE [dbo].[PG_CI_ARCUSFIL_SQL] 0, 139, 'UNIVERSAL TRIM INC', 'UNIVERSAL TRIM INC' , 'UNIV01' , 200,221 , 54, 'MADISON HEIGHTS', 'PO BOX 71541' ,'' , '48071-0541' , '2000-01-25' , '28' , '1','','2','MCUEX','','USD','','N/A','N'
EXECUTE [dbo].[PG_CI_ARCUSFIL_SQL] 0, 139, 'BAILEY MANAGEMENT CONSULTING SERVICES', 'BAILEY MANAGEMENT CONSULTING SERVICES' , 'BMCS01' , 200,213 , 83, 'ONTARIO', '163 HERITAGE ROAD' ,'KINGSVILLE' , 'N9Y 2C7' , '2001-10-08' , '29' , '1','','2','MCUEX','','USD','','N/A','N'
EXECUTE [dbo].[PG_CI_ARCUSFIL_SQL] 0, 139, 'LEAR HERMOSILLO', 'LEAR HERMOSILLO' , 'LEAR07' , 200,260 , 26, 'NOGALES', 'LEAR CORPORATION MEXICO SA DE CV' ,'PO BOX 6323' , '85621' , '2001-10-18' , '30' , '1','','2','MCUEX','','USD','','ABN','N'
EXECUTE [dbo].[PG_CI_ARCUSFIL_SQL] 0, 139, 'VISUAL SERVICES', 'VISUAL SERVICES' , 'VISU01' , 200,221 , 54, 'BLOOMFIELD HILLS', '41000 WOODWARD AVENUE' ,'' , '48304-2263' , '2001-11-18' , '31' , '1','','2','MFUEX','','USD','','N/A','N'
EXECUTE [dbo].[PG_CI_ARCUSFIL_SQL] 0, 139, 'JCIM MEXICO PROPERTIES,S.de R.L.', 'JOHNSON CONTROLS MEXICO' , 'JOHN01' , 200,260 , 8, 'JUAREZ', 'EPSILON 6525' ,'PARQUE INDUSTRIAL OMEGA' , '32320' , '2002-01-22' , '32' , '1','','2','MFUEX','','USD','RICARDO.PEREZ@JCI.COM','N/A','N'
EXECUTE [dbo].[PG_CI_ARCUSFIL_SQL] 0, 139, 'CASH SALES MEXICO', 'CASH SALES MEXICO' , 'CASH01' , 0,0 , 0, '', '' ,'' , '0' , '2002-01-28' , '33' , '1','','2','MISC ','','USD','','','N'
EXECUTE [dbo].[PG_CI_ARCUSFIL_SQL] 0, 139, 'IRVIN AUTOMOTIVE', 'JAROPAMEX ACUNA, PLANT1' , 'IRVI03' , 200,221 , 75, 'DEL RIO', '2A FAWCETT DRIVE' ,'' , '78840' , '2003-11-06' , '34' , '1','','2','MFUEX','','USD','FOB SHIP POINT','N/A','N'
EXECUTE [dbo].[PG_CI_ARCUSFIL_SQL] 0, 139, 'TENNMEX INC', 'TENNMEX INC' , 'TENN01' , 200,221 , 75, '', '2262 SAN JUAN DRIVE' ,'EAGLE PASS' , '78852' , '2005-08-15' , '35' , '1','','2','MCUEX','','USD','','N/A','N'
EXECUTE [dbo].[PG_CI_ARCUSFIL_SQL] 0, 139, 'WOODBRIDGE FOAM CORPORATION', 'WOODBRIDGE FOAM CORPORATION' , 'WOOD01' , 200,260 , 5, 'RAMOS ARIZPE', 'SALTILLO MONTERREY KM1150' ,'PARQUE INDUSTRIAL RAMOS ARIZPE' , '25900' , '2006-01-30' , '36' , '1','','2','MFUEX','','USD','','N/A','N'
EXECUTE [dbo].[PG_CI_ARCUSFIL_SQL] 0, 139, 'JOHNSON CONTROLS-EDIASA 3', 'JOHNSON CONTROLS-EDIASA 3' , 'JOHN03' , 200,221 , 75, 'EL PASO', 'JOHNSON CONTROLS INC' ,'SSC ACCOUNTS PAYABLE' , '981700' , '2006-12-20' , '37' , '1','','2','MCUEX','','USD','','N/A','N'
EXECUTE [dbo].[PG_CI_ARCUSFIL_SQL] 0, 139, 'JOHNSON CONTROL SHANGAI', 'JOHNSON CONTROL SHANGAI' , 'JOHN04' , 200,221 , 75, 'EL PASO', 'SSC ACCOUNTS PAYABLE -18438' ,'PO BOX 981700' , '79998' , '2007-01-18' , '38' , '1','','11','MCUEX','','USD','','','N'
EXECUTE [dbo].[PG_CI_ARCUSFIL_SQL] 0, 139, 'KONGSBERG AUTOMOTIVE', 'KONGSBERG AUTOMOTIVE' , 'KONG01' , 200,221 , 75, 'PHARR', 'LAREDO FREIGHT - KONGSBERG AUTOMOTIVE' ,'9208 SOUTH CAGE BLVD' , '78577' , '2008-01-29' , '39' , '1','','2','MCUEX','','USD','EXW','N/A','N'
EXECUTE [dbo].[PG_CI_ARCUSFIL_SQL] 0, 139, 'GRAMMER AUTOMOTIVE PUEBLA', 'GRAMMER AUTOMOTIVE PUEBLA' , 'GRAM01' , 200,260 , 29, 'TETLA', 'BOULEVARD TETLA NO 107' ,'Cd. Industrial Xicohtencatl' , '90434' , '2008-02-06' , '40' , '1','','2','MCUEX','','USD','FOB Juarez','N/A','N'
EXECUTE [dbo].[PG_CI_ARCUSFIL_SQL] 0, 139, 'MAY & SCOFIELD', 'MAY & SCOFIELD' , 'MAYS01' , 200,221 , 54, 'FOWLERVILLE', '445 E. VAN RIPER' ,'' , '48836' , '2008-03-05' , '41' , '1','','2','MCUEX','','USD','','','N'
EXECUTE [dbo].[PG_CI_ARCUSFIL_SQL] 0, 139, 'RECICLADOS ECOLOGICOS DIVERSOS', 'RECICLADOS ECOLOGICOS DIVERSOS' , 'CASH02' , 200,260 , 8, 'JUAREZ', 'CALLE PASCUAL OROZCO 591' ,'COL. SANTA MARIA' , '32676' , '2013-01-15' , '42' , '1','','2','MISC ','','USD','','','N'
EXECUTE [dbo].[PG_CI_ARCUSFIL_SQL] 0, 139, 'PEARL LEATHER GROUP LLC', 'PEARL LEATHER GROUP LLC' , 'PEARL01' , 200,221 , 64, 'MANHASSET', '390 PLANDOME ROAD' ,'' , '11030' , '2013-01-24' , '43' , '1','','2','MISC ','','USD','','','N'
EXECUTE [dbo].[PG_CI_ARCUSFIL_SQL] 0, 139, 'PEARL LEATHER SALES', 'PEARL LEATHER SALES' , 'PSALES' , 200,221 , 54, 'BIRMINGHAM', '523 ARGYLE' ,'' , '48009' , '2015-08-31' , '44' , '1','','2','MCUEX','','USD','','','N'
EXECUTE [dbo].[PG_CI_ARCUSFIL_SQL] 0, 139, 'PEARL LEATHER FINISHERS', 'PEARL LEATHER FINISHERS' , 'PLFNY1' , 200,221 , 64, 'JOHNSTOWN', '11-21 INDUSTRIAL PARK' ,'' , '12095' , '2015-08-31' , '45' , '1','','2','MCUEX','','USD','','','N'
EXECUTE [dbo].[PG_CI_ARCUSFIL_SQL] 0, 139, 'AUTOMOTIVE LEATHER GROUP', 'AUTOMOTIVE LEATHER GROUP' , 'ALGRP1' , 200,221 , 64, 'GREAT NECK STATES', '17 BARSTOWN ROAD' ,'' , '11021' , '2015-08-31' , '46' , '1','BKAMALI@KAMALIGROUP.COM','2','MCUEX','','USD','','','N'
EXECUTE [dbo].[PG_CI_ARCUSFIL_SQL] 0, 139, 'MAGNA SEATING', 'MAGNA SEATING OF AMERICA INC' , 'MAGN04' , 200,221 , 75, 'DEL RIO', '2199 SPUR 239' ,'MAILING TO: P.O BOX 420699' , '78840' , '2015-08-31' , '47' , '1','','2','MCUEX','','USD','','','N'
EXECUTE [dbo].[PG_CI_ARCUSFIL_SQL] 0, 139, 'KAMALI GROUP INCORPORATED', 'KAMALI GROUP INCORPORATED' , 'KAMA01' , 200,221 , 64, 'GREAT NECK', '17 BARSTOW ROAD' ,'' , '11021' , '2015-12-07' , '48' , '1','','2','MISC ','','USD','','','N'
EXECUTE [dbo].[PG_CI_ARCUSFIL_SQL] 0, 139, 'BILTMORE CORPORATION', 'BILTMORE CORPORATION' , 'BILT01' , 200,221 , 64, 'GREAT NECK', '17 BARSTOW RD.' ,'SUITE 206' , '11021' , '2016-12-08' , '49' , '1','','2','MISC ','','AUD','','','N'
EXECUTE [dbo].[PG_CI_ARCUSFIL_SQL] 0, 139, 'RICARDO VALTIERRA HERNANDEZ', 'RICARDO VALTIERRA HERNANDEZ' , 'VALT01' , 200,260 , 8, 'JUAREZ', 'FRAY GARCIA DE SAN FRANCISCO NO. 880' ,'COL. BELLAVISTA' , '32000' , '2019-03-19' , '50' , '1','','2','MFUEX','','USD','','','N'
EXECUTE [dbo].[PG_CI_ARCUSFIL_SQL] 0, 139, 'FAURECIA AUTOMOTIVE SEATING INC.', 'FAURECIA AUTOMOTIVE SEATING INC.' , 'FAUR01' , 200,221 , 54, 'AUBURN HILLS', 'TROY_1402' ,'' , '48321' , '2019-11-11' , '51' , '1','','2','MCUEX','','USD','','','N'
EXECUTE [dbo].[PG_CI_ARCUSFIL_SQL] 0, 139, '(NO-ARCUSFIL)', '( N/C )' , 'XXXX00' , 0,0 , 0, '(NO-ARCUSFIL)', '(NO-ARCUSFIL)' ,'(NO-ARCUSFIL)' , '0' , '2000-01-01' , '52' , '1','','2','MCUEX','','USD','','','N'
EXECUTE [dbo].[PG_CI_ARCUSFIL_SQL] 0, 139, 'YANFENG AUTOMOTIVE INTERIOR', 'YANFENG AUTOMOTIVE INTERIOR' , 'YANG02' , 200,221 , 54, 'ROAD NOV', '1935 WEST 12 MILE ROAD NOVI, MI 48377' ,'' , '48152' , '2019-11-19' , '53' , '1','','2','MCUEX','','USD','','','N'
EXECUTE [dbo].[PG_CI_ARCUSFIL_SQL] 0, 139, 'GRAMMER INDUSTRIES, INC', '' , 'GRAM04' , 200,221 , 54, 'TROY', '1975 TECHNOLOGY DR' ,'' , '48083' , '2019-11-19' , '54' , '1','','2','MCUEX','','USD','','','N'
EXECUTE [dbo].[PG_CI_ARCUSFIL_SQL] 0, 139, 'WPI', '' , 'WPI003' , 200,221 , 54, 'WILLIAMSTON', 'WILLIAMSTON PRODUCTS,INC' ,'845 PROGRESS CT' , '48895' , '2019-12-04' , '55' , '1','','2','MCUEX','','USD','','','N'
EXECUTE [dbo].[PG_CI_ARCUSFIL_SQL] 0, 139, 'DAIMAY AUTOMOTIVE INTERIOR, S. DE R.L. D', 'DAIMAY AUTOMOTIVE INTE' , 'DAIM05' , 200,260 , 5, 'RAMOS ARZIPE', 'AVE. CENZONTLE ESQ. HALCON' ,'CARRETERA MONCLOVA #7' , '0' , '2020-02-05' , '56' , '1','OFFICE@DAIMAYUS.COM','2','MCUEX','','USD','','','N'
EXECUTE [dbo].[PG_CI_ARCUSFIL_SQL] 0, 139, 'Eissmann Automotive de Mexico', 'EISSMANN AUTOMOTIVE DE MEXICO' , 'EISS01' , 200,260 , 29, 'PANZACOLA', 'Reforma Sur No. 27' ,'Nave 1' , '90796' , '2020-09-01' , '57' , '1','','2','MCUEX','','USD','','','N'
EXECUTE [dbo].[PG_CI_ARCUSFIL_SQL] 0, 139, 'YANGFENG AUTOMOTIVE INTERIOR SYSTEMS(THAILAND) CO.,LTD', 'YANGFENG AUTOMOTIVE INTERIOR SYSTEMS(THAILAND) CO.,LTD' , 'YANG03' , 300,349 , 123, 'CHONBURI', '700/20 WHA EASTERN SEABOARD INDUSTRIAL' ,'1 MOO 7 TAMBOL KAOKANSONG, AMPHUR SRIRACH' , '700/20' , '2020-11-19' , '58' , '1','','11','MCUEX','','USD','','','N'
EXECUTE [dbo].[PG_CI_ARCUSFIL_SQL] 0, 139, 'ADIENT US LLC', '' , 'ADIE01' , 200,221 , 54, 'PLYMOUTH', '49200 HALYARD DRIVE.PLYMOUTH,' ,'' , '49200' , '2020-12-16' , '59' , '1','','2','MCUEX','','USD','','','N'
EXECUTE [dbo].[PG_CI_ARCUSFIL_SQL] 0, 139, 'YANFENG AUTOMOTIVE INTER S. (THAILAND)', 'YANFENG AUTOMOTIVE INTER S. (THAILAND)' , 'YANG04' , 300,349 , 123, 'CHONBURI', '700/20 WHA EASTERN SEABOARD INDUSTRIAL' ,'1 MOO 7 TAMBOL KAOKANSONG,AMPHUR SRIRACH' , '700/20' , '2021-01-11' , '60' , '1','','5','MFUEX','','USD','','','N'
-- =================================================================================
GO

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[PG_CI_ARCUSFIL_CONTACT]') AND TYPE IN (N'P', N'PC'))
	DROP PROCEDURE [DBO].[PG_CI_ARCUSFIL_CONTACT]
GO

-- //////////////////////////////////////////////////////////////
-- //				CI - ARCUSFIL
-- //////////////////////////////////////////////////////////////
		 --EXECUTE [DBO].[PG_CI_ARCUSFIL_CONTACT] 0, 0, 45, 'JOHN RUGGIERO' ,'5187624543' ,'' ,'JRUGGIERO@PEARLLEATHER.COM' ,'' ,''
CREATE PROCEDURE [DBO].[PG_CI_ARCUSFIL_CONTACT]
	@PP_K_SISTEMA_EXE					INT,
	@PP_K_USUARIO_ACCION				INT,
	-- ===========================
	@PP_A4GLIdentity								INT,
	@PP_D_ARCUSFIL_CONTACT_NAME					VARCHAR(255),
	-- ============================
	@PP_ARCUSFIL_CONTACT_PHONE_01				VARCHAR(25),
	@PP_ARCUSFIL_CONTACT_PHONE_01_EXT			VARCHAR(25),
	@PP_ARCUSFIL_CONTACT_EMAIL_01				VARCHAR(150),
	@PP_ARCUSFIL_CONTACT_FAX_01					VARCHAR(25),
	-- ============================
	@PP_C_ARCUSFIL_CONTACT						VARCHAR(500)
AS				
	INSERT INTO ARCUSFIL_CONTACT
			(	[A4GLIdentity],
				[D_ARCUSFIL_CONTACT_NAME],
				-- ============================
				[ARCUSFIL_CONTACT_PHONE_01],
				[ARCUSFIL_CONTACT_PHONE_01_EXT],
				[ARCUSFIL_CONTACT_FAX_01],
				[ARCUSFIL_CONTACT_EMAIL_01],
				-- ============================
				[C_ARCUSFIL_CONTACT],
				-- ===========================
				[K_USUARIO_ALTA], [F_ALTA], [K_USUARIO_CAMBIO], [F_CAMBIO],
				[L_BORRADO], [K_USUARIO_BAJA], [F_BAJA]  )
	VALUES	
			(	@PP_A4GLIdentity,
				@PP_D_ARCUSFIL_CONTACT_NAME,
				-- ============================
				@PP_ARCUSFIL_CONTACT_PHONE_01,
				@PP_ARCUSFIL_CONTACT_PHONE_01_EXT,
				@PP_ARCUSFIL_CONTACT_FAX_01,
				@PP_ARCUSFIL_CONTACT_EMAIL_01,	
				-- ============================
				@PP_C_ARCUSFIL_CONTACT,
				-- ===========================
				@PP_K_USUARIO_ACCION, GETDATE(), @PP_K_USUARIO_ACCION, GETDATE(),
				0, NULL, NULL  )
GO

EXECUTE [DBO].[PG_CI_ARCUSFIL_CONTACT] 0, 0, 59, 'MAURICIO ESPINOSA', '18773348706' , '' , '' , '', ''
EXECUTE [DBO].[PG_CI_ARCUSFIL_CONTACT] 0, 0, 49, 'RUTH KAMALI', '5166274000' , '' , '' , '', ''
EXECUTE [DBO].[PG_CI_ARCUSFIL_CONTACT] 0, 0, 29, 'BMCS01', '5197333713' , '' , '' , '5197335887', ''
EXECUTE [DBO].[PG_CI_ARCUSFIL_CONTACT] 0, 0, 42, 'ROGELIO CORRAL', '6563827522' , '' , '' , '', ''
EXECUTE [DBO].[PG_CI_ARCUSFIL_CONTACT] 0, 0, 1, 'NIKKI OSTERLAND', '2485857700' , '' , '' , '2485855800', ''
EXECUTE [DBO].[PG_CI_ARCUSFIL_CONTACT] 0, 0, 2, 'EBIN01', '9783565701' , '' , '' , '9783569832', ''
EXECUTE [DBO].[PG_CI_ARCUSFIL_CONTACT] 0, 0, 3, 'LUIS ENRIQUE HERNANDEZ', '' , '' , '' , '', ''
EXECUTE [DBO].[PG_CI_ARCUSFIL_CONTACT] 0, 0, 51, 'ACCOUNTS PAYABLE', '' , '' , '' , '', ''
EXECUTE [DBO].[PG_CI_ARCUSFIL_CONTACT] 0, 0, 4, 'FIND01', '4194245429' , '' , '' , '4194223164', ''
EXECUTE [DBO].[PG_CI_ARCUSFIL_CONTACT] 0, 0, 5, 'WILLIS I SIMMONS', '9416766081' , '' , '' , '9416766463', ''
EXECUTE [DBO].[PG_CI_ARCUSFIL_CONTACT] 0, 0, 6, 'ROSA BOURDEAU', '' , '' , '' , '', ''
EXECUTE [DBO].[PG_CI_ARCUSFIL_CONTACT] 0, 0, 40, 'CLEMENCIA VIVEROS', '522414184600' , '3654' , '' , '522414127291', ''
EXECUTE [DBO].[PG_CI_ARCUSFIL_CONTACT] 0, 0, 7, 'MARIA CLABORN', '12484514216' , '' , '' , '', ''
EXECUTE [DBO].[PG_CI_ARCUSFIL_CONTACT] 0, 0, 34, 'LISA BETH RUMPL', '2484514276' , '' , '' , '2484514230', ''
EXECUTE [DBO].[PG_CI_ARCUSFIL_CONTACT] 0, 0, 8, 'JITC01', '5252847224' , '' , '' , '5252847231', ''
EXECUTE [DBO].[PG_CI_ARCUSFIL_CONTACT] 0, 0, 32, 'RICARDO PEREZ', '015552847154' , '' , '' , '015552847210', ''
EXECUTE [DBO].[PG_CI_ARCUSFIL_CONTACT] 0, 0, 37, 'BETHANY SCOTT', '' , '' , '' , '', ''
EXECUTE [DBO].[PG_CI_ARCUSFIL_CONTACT] 0, 0, 38, 'MIKE CHOPSON', '' , '' , '' , '', ''
EXECUTE [DBO].[PG_CI_ARCUSFIL_CONTACT] 0, 0, 48, 'RUTH KAMALI', '' , '' , '' , '', ''
EXECUTE [DBO].[PG_CI_ARCUSFIL_CONTACT] 0, 0, 39, 'DAVE SCHUTTER', '12486153090' , '' , '' , '12486153098', ''
EXECUTE [DBO].[PG_CI_ARCUSFIL_CONTACT] 0, 0, 10, 'STEVE KRAFT', '5175457500' , '' , '' , '5175458199', ''
EXECUTE [DBO].[PG_CI_ARCUSFIL_CONTACT] 0, 0, 11, 'LEAR05', '9154994545' , '' , '' , '9158495610', ''
EXECUTE [DBO].[PG_CI_ARCUSFIL_CONTACT] 0, 0, 30, 'DAVID RAMOS', '' , '' , '' , '', ''
EXECUTE [DBO].[PG_CI_ARCUSFIL_CONTACT] 0, 0, 12, 'CATHY SADLER', '' , '' , '' , '', ''
EXECUTE [DBO].[PG_CI_ARCUSFIL_CONTACT] 0, 0, 14, 'MS DANIELA OLEJNIK', '13137554909' , '' , '' , '13137554898', ''
EXECUTE [DBO].[PG_CI_ARCUSFIL_CONTACT] 0, 0, 15, 'LEGM01', '8105780400' , '' , '' , '', ''
EXECUTE [DBO].[PG_CI_ARCUSFIL_CONTACT] 0, 0, 16, 'LILA MACKEY', '3135939000' , '' , '' , '3132535041', ''
EXECUTE [DBO].[PG_CI_ARCUSFIL_CONTACT] 0, 0, 17, 'DOUG DEATON', '0115286130319' , '' , '' , '', ''
EXECUTE [DBO].[PG_CI_ARCUSFIL_CONTACT] 0, 0, 19, 'MARILY BURKE', '' , '' , '' , '', ''
EXECUTE [DBO].[PG_CI_ARCUSFIL_CONTACT] 0, 0, 41, 'LISA FIRTH', '5172236734' , '' , '' , '5172231331', ''
EXECUTE [DBO].[PG_CI_ARCUSFIL_CONTACT] 0, 0, 20, 'VITO PALADINO', '' , '' , '' , '', ''
EXECUTE [DBO].[PG_CI_ARCUSFIL_CONTACT] 0, 0, 21, 'MIHO NAKATANI', '' , '' , '' , '', ''
EXECUTE [DBO].[PG_CI_ARCUSFIL_CONTACT] 0, 0, 22, 'MCDO01', '0755914911' , '' , '' , '0755914983', ''
EXECUTE [DBO].[PG_CI_ARCUSFIL_CONTACT] 0, 0, 23, 'MCDO02', '0755914911' , '' , '' , '0755914983', ''
EXECUTE [DBO].[PG_CI_ARCUSFIL_CONTACT] 0, 0, 24, 'PATTY O´DELL', '3139636114' , '' , '' , '', ''
EXECUTE [DBO].[PG_CI_ARCUSFIL_CONTACT] 0, 0, 25, 'MR. KURT GREASER', '001113174845555' , '' , '' , '001513174845565', ''
EXECUTE [DBO].[PG_CI_ARCUSFIL_CONTACT] 0, 0, 43, 'SELENA LAU', '5166274000' , '' , '' , '', ''
EXECUTE [DBO].[PG_CI_ARCUSFIL_CONTACT] 0, 0, 45, 'JOHN RUGGIERO', '5187624543' , '' , 'JRUGGIERO@PEARLLEATHER.COM' , '', ''				---FALTA
EXECUTE [DBO].[PG_CI_ARCUSFIL_CONTACT] 0, 0, 44, 'BILL REID', '2485057417' , '' , 'WILLIAM.A.REID@ATT.NET' , '', ''
EXECUTE [DBO].[PG_CI_ARCUSFIL_CONTACT] 0, 0, 27, 'CECILIA RODRIGUEZ', '' , '' , '' , '', ''
EXECUTE [DBO].[PG_CI_ARCUSFIL_CONTACT] 0, 0, 35, 'NORMA GUTIERREZ', '00111528787830150' , '' , '' , '', ''
EXECUTE [DBO].[PG_CI_ARCUSFIL_CONTACT] 0, 0, 28, 'MARY KEHOE', '2485869118' , '' , '' , '2486425154', ''
EXECUTE [DBO].[PG_CI_ARCUSFIL_CONTACT] 0, 0, 50, 'RICARDO VALTIERRA', '6564011973' , '' , '' , '', ''
EXECUTE [DBO].[PG_CI_ARCUSFIL_CONTACT] 0, 0, 36, 'BRIAN TANNER', '5196763626' , '' , '' , '3139829198', ''
EXECUTE [DBO].[PG_CI_ARCUSFIL_CONTACT] 0, 0, 58, 'MR. ZHANG WENKANG', '8613061818985' , '' , '' , '', ''
EXECUTE [DBO].[PG_CI_ARCUSFIL_CONTACT] 0, 0, 60, 'YUENYONG NATTIDA', '886211963' , '' , '' , '', ''



IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[PG_CI_ARCUSFIL_ADDRESS]') AND TYPE IN (N'P', N'PC'))
	DROP PROCEDURE [DBO].[PG_CI_ARCUSFIL_ADDRESS]
GO

-- //////////////////////////////////////////////////////////////
-- //				CI - ARCUSFIL
-- //////////////////////////////////////////////////////////////

CREATE PROCEDURE [DBO].[PG_CI_ARCUSFIL_ADDRESS]
	@PP_K_SISTEMA_EXE					INT,
	@PP_K_USUARIO_ACCION				INT,
	-- ===========================
	@PP_A4GLIdentity							INT,
	@PP_K_ADDRESS_TYPE						INT,
	-- ============================
	@PP_D_ARCUSFIL_ADDRESS_NAME				VARCHAR(300),
	@PP_D_ARCUSFIL_ADDRESS_01				VARCHAR(300),
	@PP_D_ARCUSFIL_ADDRESS_02				VARCHAR(300),
	@PP_D_ARCUSFIL_ADDRESS_03				VARCHAR(300),
	@PP_D_ARCUSFIL_ADDRESS_04				VARCHAR(300),
	-- ============================
	@PP_L_ARCUSFIL_ADDRESS_MAIN				INT
AS

	INSERT INTO ARCUSFIL_ADDRESS
			(	[A4GLIdentity],
				[K_ADDRESS_TYPE],
				-- =========================
				[D_ARCUSFIL_ADDRESS_NAME],
				[D_ARCUSFIL_ADDRESS_01],
				[D_ARCUSFIL_ADDRESS_02],
				[D_ARCUSFIL_ADDRESS_03],
				[D_ARCUSFIL_ADDRESS_04],
				[L_ARCUSFIL_ADDRESS_MAIN],
				-- ===========================
				[K_USUARIO_ALTA], [F_ALTA], [K_USUARIO_CAMBIO], [F_CAMBIO],
				[L_BORRADO], [K_USUARIO_BAJA], [F_BAJA]  )
	VALUES	
			(	@PP_A4GLIdentity,
				@PP_K_ADDRESS_TYPE,
				-- ============================
				@PP_D_ARCUSFIL_ADDRESS_NAME,
				@PP_D_ARCUSFIL_ADDRESS_01,
				@PP_D_ARCUSFIL_ADDRESS_02,
				@PP_D_ARCUSFIL_ADDRESS_03,
				@PP_D_ARCUSFIL_ADDRESS_04,
				@PP_L_ARCUSFIL_ADDRESS_MAIN,
				-- ===========================
				@PP_K_USUARIO_ACCION, GETDATE(), @PP_K_USUARIO_ACCION, GETDATE(),
				0, NULL, NULL  )
GO

EXECUTE [DBO].[PG_CI_ARCUSFIL_ADDRESS] 0, 0, 56, '1', 'DAIMAY AUTOMOTIVE INTERIOR, S DE R.L. DE' , 'AVE. CENZONTLE ESQ. HALCON' , 'CARRETERA MONCLOVA #7' , 'PARQUE INDUSTRIAL FINSA', 'RAMOS ARZIPE COAH', '1'
EXECUTE [DBO].[PG_CI_ARCUSFIL_ADDRESS] 0, 0, 56, '2', 'DAIMAY AUTOMOTIVE INTERIOR, S DE R.L. DE' , 'AVE. CENZONTLE ESQ. HALCON' , 'CARRETERA MONCLOVA #7' , 'PARQUE INDUSTRIAL FINSA', 'RAMOS ARZIPE COAH', '1'
EXECUTE [DBO].[PG_CI_ARCUSFIL_ADDRESS] 0, 0, 57, '1', 'EISSMANN AUTOMOTIVE DE MEXICO' , 'REFORMA SUR NO. 27' , 'NAVE 1' , 'PANZACOLA, 90796', 'MEXICO', '1'
EXECUTE [DBO].[PG_CI_ARCUSFIL_ADDRESS] 0, 0, 57, '2', 'EISSMANN AUTOMOTIVE DE MEXICO' , 'REFORMA SUR NO. 27' , 'NAVE 1' , 'PANZACOLA, 90796', 'MEXICO', '1'
EXECUTE [DBO].[PG_CI_ARCUSFIL_ADDRESS] 0, 0, 34, '1', 'IRVIN AUTOMOTIVE PRODUCTS, LLC' , '2A FAWCETT DR.' , 'DEL RIO, TX 78840' , 'UNITED STATES', '', '1'
EXECUTE [DBO].[PG_CI_ARCUSFIL_ADDRESS] 0, 0, 34, '2', 'IRVIN AUTOMOTIVE PRODUCTS, LLC' , '2A FAWCETT DR.' , 'DEL RIO, TX 78840' , 'UNITED STATES', '', '1'
EXECUTE [DBO].[PG_CI_ARCUSFIL_ADDRESS] 0, 0, 18, '1', 'MAGNA SEATING OF AMERICA INC' , '2199 SPUR 239' , 'MAILING TO: P.O. BOX 420699' , 'DEL RIO TX 78840', 'USA', '1'
EXECUTE [DBO].[PG_CI_ARCUSFIL_ADDRESS] 0, 0, 18, '2', 'MAGNA SEATING OF AMERICA INC' , '2199 SPUR 239' , 'MAILING TO: P.O. BOX 420699' , 'DEL RIO TX 78840', 'USA', '1'
EXECUTE [DBO].[PG_CI_ARCUSFIL_ADDRESS] 0, 0, 19, '1', 'SEATING SYS.OF ACUNA DIV INTIER AUTO' , '2199 SPUR 239' , 'P.O. BOX 420699' , 'DEL RIO, TX 78840', 'USA', '1'
EXECUTE [DBO].[PG_CI_ARCUSFIL_ADDRESS] 0, 0, 19, '2', 'SEATING SYS.OF ACUNA DIV INTIER AUTO' , '2199 SPUR 239' , 'P.O. BOX 420699' , 'DEL RIO, TX 78840', 'USA', '1'
EXECUTE [DBO].[PG_CI_ARCUSFIL_ADDRESS] 0, 0, 36, '1', 'SALTILLO INTERIOR TRIM SA DE CV' , 'AUTOPISTA SALTILLO-MONTERREY KM 11.50' , 'PARQUE INDUSTRIAL RAMOS ARIZPE' , 'COAHUILA, CP 25900', '', '1'
EXECUTE [DBO].[PG_CI_ARCUSFIL_ADDRESS] 0, 0, 36, '2', 'SALTILLO INTERIOR TRIM SA DE CV' , 'AUTOPISTA SALTILLO-MONTERREY KM 11.50' , 'PARQUE INDUSTRIAL RAMOS ARIZPE' , 'COAHUILA, CP 25900', '', '1'
EXECUTE [DBO].[PG_CI_ARCUSFIL_ADDRESS] 0, 0, 55, '1', 'WPI' , '845 PROGRESS CT. WILLIAMSTON, MI 48895' , 'WILLIAMSTON, MI' , '', '', '1'
EXECUTE [DBO].[PG_CI_ARCUSFIL_ADDRESS] 0, 0, 55, '2', 'WPI' , '845 PROGRESS CT. WILLIAMSTON, MI 48895' , 'WILLIAMSTON, MI' , '', '', '1'
EXECUTE [DBO].[PG_CI_ARCUSFIL_ADDRESS] 0, 0, 53, '1', 'YANFENG MEXICO' , 'PO BOX 7148' , '48376 NOVI MI' , 'UNITED STATES', '', '1'
EXECUTE [DBO].[PG_CI_ARCUSFIL_ADDRESS] 0, 0, 53, '2', 'YANFENG MEXICO' , 'PO BOX 7148' , '48376 NOVI MI' , 'UNITED STATES', '', '1'
EXECUTE [DBO].[PG_CI_ARCUSFIL_ADDRESS] 0, 0, 58, '1', 'YANGFENG AUTOMOTIVE INTERIOR SYSTEMS(THAILAND) CO.,LTD' , '700/20 WHA EASTERN SEABOARD INDUSTRIAL' , '1 M00 7 TAMBOL KHAO KHAN SONG, AMPHUR SRIRACHA' , 'CHONBURI, 700/20', 'THAILAND TAX ID:0205562018045', '1'
EXECUTE [DBO].[PG_CI_ARCUSFIL_ADDRESS] 0, 0, 58, '2', 'YANGFENG AUTOMOTIVE INTERIOR SYSTEMS(THAILAND) CO.,LTD' , '700/20 WHA EASTERN SEABOARD INDUSTRIAL' , '1 M00 7 TAMBOL KHAO KHAN SONG, AMPHUR SRIRACHA' , 'CHONBURI, 700/20', 'THAILAND TAX ID:0205562018045', '1'
