-- //////////////////////////////////////////////////////////////
-- // DATA BASE:		DATA_02
-- // MODULE:			APQP_MODEL
-- // OPERATION:		TABLA
-- //////////////////////////////////////////////////////////////
-- // AUTHOR:			AX
-- // CREATION DATE:	20210122
-- ////////////////////////////////////////////////////////////// 

--USE [DATA_02]
GO

-- //////////////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////////////
-- // DROPs
-- //////////////////////////////////////////////////////////////
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ARCUSFIL_PROGRAM]') AND type in (N'U'))
	DROP TABLE [dbo].[ARCUSFIL_PROGRAM]
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ARCUSFIL_PROGRAM_MODEL]') AND type in (N'U'))
	DROP TABLE [dbo].[ARCUSFIL_PROGRAM_MODEL]
GO


-- ////////////////////////////////////////////////////////////////
-- //					ARCUSFIL_PROGRAM_MODEL				 
-- ////////////////////////////////////////////////////////////////

CREATE TABLE [dbo].[ARCUSFIL_PROGRAM_MODEL] (
	[K_ARCUSFIL_PROGRAM_MODEL]				[INT]			IDENTITY (1,1)	NOT NULL,
	[D_ARCUSFIL_PROGRAM_MODEL]				[VARCHAR](255)	NOT NULL,
	[S_ARCUSFIL_PROGRAM_MODEL]				[VARCHAR](20)	NOT NULL,
	-- ===========================
	[K_ARCUSFIL_PROGRAM]					[INT]			NOT NULL,
	-- ===========================
	[ARCUSFIL_PROGRAM_MODEL_TYPE]			[VARCHAR](255)	NOT NULL DEFAULT '',
	[ARCUSFIL_PROGRAM_MODEL_YEAR]			[VARCHAR](20)	NOT NULL DEFAULT '',
	[ARCUSFIL_PROGRAM_MODEL_MAKER]			[VARCHAR](255)	NOT NULL DEFAULT '',
) ON [PRIMARY]
GO
-- //////////////////////////////////////////////////////
ALTER TABLE [dbo].[ARCUSFIL_PROGRAM_MODEL]
	ADD CONSTRAINT [PK_ARCUSFIL_PROGRAM_MODEL]
		PRIMARY KEY CLUSTERED ([K_ARCUSFIL_PROGRAM_MODEL])
GO
ALTER TABLE [dbo].[ARCUSFIL_PROGRAM_MODEL]
ADD
			[K_USUARIO_ALTA]					[INT] NOT NULL,
			[F_ALTA]							[DATETIME] NOT NULL,
			[K_USUARIO_CAMBIO]					[INT] NOT NULL,
			[F_CAMBIO]							[DATETIME] NOT NULL,
			[L_BORRADO]							[INT] NOT NULL,
			[K_USUARIO_BAJA]					[INT] NULL,
			[F_BAJA]							[DATETIME] NULL;
GO


-- ////////////////////////////////////////////////////////////////
-- //					ARCUSFIL_PROGRAM				 
-- ////////////////////////////////////////////////////////////////

CREATE TABLE [dbo].[ARCUSFIL_PROGRAM] (
	[K_ARCUSFIL_PROGRAM]				[INT]			IDENTITY (1,1)	NOT NULL,
	[S_ARCUSFIL_PROGRAM]				[VARCHAR](20)	NOT NULL,
	[O_ARCUSFIL_PROGRAM]				[INT]			NOT NULL DEFAULT 15,
	[L_ARCUSFIL_PROGRAM]				[INT]			NOT NULL DEFAULT 1,
	-- ===========================
	[K_ARCUSFIL]						[INT]			NOT NULL
) ON [PRIMARY]
GO
-- //////////////////////////////////////////////////////
ALTER TABLE [dbo].[ARCUSFIL_PROGRAM]
	ADD CONSTRAINT [PK_ARCUSFIL_PROGRAM]
		PRIMARY KEY CLUSTERED ([K_ARCUSFIL_PROGRAM])
GO

ALTER TABLE [dbo].[ARCUSFIL_PROGRAM]
ADD
			[K_USUARIO_ALTA]					[INT] NOT NULL,
			[F_ALTA]							[DATETIME] NOT NULL,
			[K_USUARIO_CAMBIO]					[INT] NOT NULL,
			[F_CAMBIO]							[DATETIME] NOT NULL,
			[L_BORRADO]							[INT] NOT NULL,
			[K_USUARIO_BAJA]					[INT] NULL,
			[F_BAJA]							[DATETIME] NULL;
GO

-- //////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_CI_ARCUSFIL_PROGRAM]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_CI_ARCUSFIL_PROGRAM]
GO
-- //////////////////////////////////////////////////////////////
-- //				CI - ARCUSFIL_PROGRAM
-- //////////////////////////////////////////////////////////////
CREATE PROCEDURE [dbo].[PG_CI_ARCUSFIL_PROGRAM]
	@PP_K_SISTEMA_EXE					INT,
	@PP_K_USUARIO_ACCION				INT,
	-- ===========================
	@PP_K_ARCUSFIL						INT,
	-- ===========================
	@PP_S_ARCUSFIL_PROGRAM				VARCHAR(20)
	-- ===========================
AS
	-- ===========================
	INSERT INTO ARCUSFIL_PROGRAM
			(	[S_ARCUSFIL_PROGRAM],
				-- ===========================
				[K_ARCUSFIL],
				-- ===========================
				[K_USUARIO_ALTA], [F_ALTA], [K_USUARIO_CAMBIO], [F_CAMBIO],
				[L_BORRADO], [K_USUARIO_BAJA], [F_BAJA]		)
	VALUES	
			(	LTRIM(RTRIM(@PP_S_ARCUSFIL_PROGRAM)),
				-- ===========================
				@PP_K_ARCUSFIL,
				-- ===========================
				@PP_K_USUARIO_ACCION, GETDATE(), @PP_K_USUARIO_ACCION, GETDATE(),
				0, NULL, NULL  )
	-- //////////////////////////////////////////////////////////////
GO
-- ===================================================================================================================
SET NOCOUNT OFF
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 46, 'WL'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 1, 'U377'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 56, 'WK'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 57, 'WL'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 51, 'WS'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 5, 'U364'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 40, 'U388'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 54, 'WL'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 54, 'WS'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 7, 'GMT'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 7, 'JL'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 7, 'JT'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 7, 'U387'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 7, 'U388'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 7, 'V229'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 7, 'WL'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 34, 'GMT'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 32, 'U388'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 9, 'GM360'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 9, 'JCI'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 37, 'GM360'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 37, 'P415'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 37, 'U228'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 38, 'GM360'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 39, 'U388'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 13, 'D258'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 13, 'GMX365'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 13, 'S197'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 17, 'GMX001'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 17, 'U204'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 17, 'U364'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 17, 'U377'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 17, 'U553'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 17, 'VN127'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 18, 'WL'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 19, 'D471'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 19, 'GMT'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 19, 'RU'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 19, 'U387'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 19, 'U388'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 19, 'U540'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 19, 'WD'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 19, 'WK'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 19, 'WS'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 41, 'U388'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 27, 'U228'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 36, 'RU'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 55, 'WPI'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 53, 'WS'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 58, 'WL'
SET NOCOUNT ON

--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'WD7','2021 WL DL 75 VPD',46
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, '77H','U377 FORD HEADREST',1
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'WDK','2021 WK WD 2ND ROW ARMREST',56
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'WLE','2021 WL EISMANN',57
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'C3A','2021 WS BL-GL EEP 3RD ROW',51
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'C3B','2021 WS AL JEEP 3RD ROW',51
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'FW2','2021 WS JEEP SL NEVER QUILTED',51
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'FWS','2021 WS AL JEEP BASE',51
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'S3S','2021 WS SL JEEP 3RD ROW',51
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'S3U','2021 WS UL JEEP 3RD ROW',51
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'WS3','2021 WS UL ALWAYS QUILTED',51
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'MCY','U364 MERCURY LTD FINDALY',5
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'GAR','U388 LINCOLN ARMREST',40
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'GR1','2021 WL 75 QUADS 2ND. ROW ARMR',54
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'GR2','WS FOLDING 2ND-ROW ARM REST',54
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'GRM','2021 WL 74/75 2ND. ROW ARMREST',54
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'GW2','2021 WL 75 QUADS 2ND. ROW AR',54
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'GWL','2021 WL 74/75 2ND. ROW ARMRE',54
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'GWS','2021 WS GRAN WAGONNER',54
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, '193','GMT 193 2007',7
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, '87C','U387 FORD CUTTING EDGE',7
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, '87P','U387 FORD PREMIUM',7
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, '88A','U388 LINCOLN ARMREST',7
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, '88H','U388 HEADREST',7
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, '88L','U388 LINCOLN LIMITED',7
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'GM1','GMT 191 PONTIAC TORRENT',7
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'GM2','GMT 192 PONTIAC PERSUIT',7
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'GM3','ARMREST GMT 193',7
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'GXP','GMT 192 GXP 2008',7
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'JJT','2019 JEEP JT',7
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'JLI','2018 JEEP JL',7
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'JPH','2020 JEEP JL PHEV',7
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'JPS','2021 JEEP JL PHEV SUMMIT',7
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'JSU','JEEPJL SUMMIT',7
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'JTM','2019 JEEP JT MOJAVE',7
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'JTS','2021 JEEP JT SUMMIT',7
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'VFL','V229 FORD FREESTAR LTD',7
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'VML','V229 FREESTAR MERCURY LTD',7
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'VMP','V229 FREESTAR MPA',7
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'VMX','V229 FREESTAR MXA',7
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'WLS','WLS JEEP 2020',7
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, '191','GMT 191 2008',34
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, '192','GMT 192 2008',34
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'ARM','ARMREST GMT 193',34
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'G93','GMT 193 2008',34
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'GX2','GMT 192 GXP 2008',34
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'PL0','U388 CONSOLE',32
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, '114','EN114 CONSOLE JCI',9
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'CHI','GM360 CHEVY / ISUZU /GMC CHINA',9
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'JCT','JCI-TESLA',9
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, '228','U228 NAVIGATOR LUX/ULT',37
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, '415','P415 PLATINIUM',37
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'BUI','GM 360 BUICK',37
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'CHE','GM 360 CHEVY / ISUZU / GMC',37
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'DEN','GM 360 DENALY',37
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'GSS','GM 360 TRAILBLAZER SS',37
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'NAV','U228 NAVIGATOR LUX EDIASA 3',37
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'SAA','GM 360 SAAB',37
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'SHA','GM 360 CHEVY/ISUZU/GMC SHANGAI',38
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'SHI','GM360 CHEVY SHANGAI',38
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'KHE','U388 HEADREST',39
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, '365','GMX 365 2008 FIXED',13
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'CAL','2013 S197 MUSTANG CALIFORNIA',13
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'G65','GMX365 BUICK LACROSSE',13
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'IUP','2013 S197 MUSTANG IUP',13
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'PRM','2013 S197 MUSTANG PREMIUM',13
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'SH1','2013 S197 MUSTANG SHELBY 5B8',13
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'SH2','2013 S197 MUSTANG SHELBY TT',13
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'THL','2013 D258 TAURUS LTD',13
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'THO','2013 D258 TAURUS SHO & LIMITED',13
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'TSL','2013 D258 TAURUS SEL',13
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'GMC','GMX 001 COUPE',17
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'GX1','GMX 001 COUPE L4',17
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'GXS','GMX001 SEDAN',17
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'HRM','U377 HEADREST 2010',17
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'MAZ','U377 MAZDA PREMIUM 2009',17
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'MP9','U377 MERCURY PREMIUM 2009',17
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'PL1','U377 FORD PREMIUM 11 PLM',17
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'PLA','VN-127 FORD ECONOLINE',17
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'U20','U204 MAZDA AIR BAG',17
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'U2F','U204 FORD LTD AB',17
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'U2L','U204 FORD LTD STD',17
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'U2M','U204 MAZDA PREMIUM',17
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'U37','U377 MERCURY LTD 2008',17
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'U3L','U364 MERCURY LTD STD',17
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'U3M','U377 MERCURY PREMIUM 2008',17
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'U3P','U364 MCY PREMIUM',17
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'U55','2019 U553 EXPEDITION',17
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'U77','U377 FORD MONO TONE',17
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'UMA','U377 MAZDA PREMIUM 2008',17
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'W7A','2021 WL 74 AL',18
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'W7B','2021 WL 74 BL',18
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'W7C','2021 WL 74 CL 8W',18
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'W7D','2021 WL 74 DL',18
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'W7E','2021 WL 74 EC',18
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'W7S','2021 WL 74 SL',18
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'W7T','2021 WL 74 TL',18
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'WAL','2021 WL 75 AL 8W LIMITED',18
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'WC1','2021 WL 75 CL 12 WAY',18
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'WCL','2021 WL 75 CL 8 WAY',18
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'WDL','2021 WL 75 DL LIMITED',18
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'WE6','2021 WL 75 E6',18
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'WEC','2021 WL 75 EC SUMMIT',18
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'WLB','2021 WL 75 BL OVERLAND',18
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'WLK','2021 WL KL 8W BASE SRT',18
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'WTL','2021 WL 75 TL 12 WAY',18
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, '387','U387 FORD PREMIUM',19
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, '3SU','GMT 315 SUV',19
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'FCE','U387 FORD CUTTING EDGE',19
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'GRE','U387 FORD GREY',19
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'L88','U388 LINCOLN LIMITED',19
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'PL2','U387 FORD SEL 2011 PLM',19
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'PL3','U388 LINCOLN BASE 2012',19
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'PL4','D471 SEL 2012',19
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'PL5','D471 LTD 2012',19
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'PL6','U388 LINCOLN ULTIMATE',19
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'PL7','U387 FORD SEL 2012',19
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'PL7','U387 FORD SEL 2013',19
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'PL8','U387 FORD SPORT 2012',19
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'PL9','U387 FORD SPORT 2011',19
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'PLB','U388 HEADREST 2012',19
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'PLC','D471 LTD PLATINIUM',19
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'PLD','D471 SEL 2013',19
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'PLE','D471 LTD 2013',19
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'PLS','D471 2016 SALERNO',19
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'PVP','U387 FORD VPP',19
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'RDL','2021 RU DL PINNACLE',19
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'RUA','2016 RU OPCION AL',19
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'RUE','2016 RU OPCION EL',19
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'RUM','2016 RU OPCION ML',19
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'SI3','3NEWMODELSIS',19
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'SL3','2013 U387 SEL',19
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'U54','U540 VINYL LAMINATION',19
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'WBL','2017 WK BL',19
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'WD2','2017 WD ML DOS TONOS',19
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'WDM','2017 WD ML',19
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'WEL','2017 WK-EL RESERVE',19
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'WKG','2014 WK JEEP GL/DL',19
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'WKJ','2017 WK CJ',19
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'WKL','2015 WK KL ALTITUDE II',19
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'WKT','2014 WK JEEP GL/DL TWO TONES',19
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'WKU','2014 WK JEEP UL',19
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'WKY','2018 WK YL',19
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'WKZ','2014 WK DZ(SRT)',19
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'WNL','2018 WK NL',19
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'WPL','2018 WD PL',19
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'WSL','2019 WS JEEP AL',19
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'XYZ','WK TEST',19
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'MYS','U388 HEADREST',41
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'THE','U228 NAVIGATOR HEADREST',27
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'RUP','2021 RU PINNACLE',36
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'WPI','2021 WPI WD CONSOLE LID',55
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'YWD','WS YANGFENG DOOR PANEL',53
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'YWS','2021 WS JEEP GRAND WAGONEER',53
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'YC4','2021 WL 74 JEEP GRAND CHEROKEE',58
--EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM]  0, 0, 'YC5','2021 WL 75 JEEP GRAND CHEROKEE',58

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]
GO
-- //////////////////////////////////////////////////////////////
-- //				CI - ARCUSFIL_PROGRAM_MODEL
-- //////////////////////////////////////////////////////////////
CREATE PROCEDURE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]
	@PP_K_SISTEMA_EXE					INT,
	@PP_K_USUARIO_ACCION				INT,
	-- ===========================
	@PP_K_ARCUSFIL_PROGRAM				INT,
	-- ===========================
	@PP_S_ARCUSFIL_PROGRAM_MODEL		VARCHAR(20),
	@PP_D_ARCUSFIL_PROGRAM_MODEL		VARCHAR(255)--,
	-- ===========================
	--@PP_ARCUSFIL_PROGRAM_MODEL_TYPE	VARCHAR(255),
	--@PP_ARCUSFIL_PROGRAM_MODEL_YEAR		VARCHAR(20),
	--@PP_ARCUSFIL_PROGRAM_MODEL_MAKER	VARCHAR(255)
AS
	-- ===========================
	INSERT INTO ARCUSFIL_PROGRAM_MODEL
			(	[D_ARCUSFIL_PROGRAM_MODEL],			
				[S_ARCUSFIL_PROGRAM_MODEL],
				-- ===========================
				[K_ARCUSFIL_PROGRAM],
				-- ===========================
				--[ARCUSFIL_PROGRAM_MODEL_TYPE],		[ARCUSFIL_PROGRAM_MODEL_YEAR],
				--[ARCUSFIL_PROGRAM_MODEL_MAKER],			
				-- ===========================
				[K_USUARIO_ALTA], [F_ALTA], [K_USUARIO_CAMBIO], [F_CAMBIO],
				[L_BORRADO], [K_USUARIO_BAJA], [F_BAJA]		)
	VALUES	
			(	LTRIM(RTRIM(@PP_D_ARCUSFIL_PROGRAM_MODEL)),			
				LTRIM(RTRIM(@PP_S_ARCUSFIL_PROGRAM_MODEL)),
				-- ===========================
				@PP_K_ARCUSFIL_PROGRAM,
				-- ===========================
				--LTRIM(RTRIM(@PP_ARCUSFIL_PROGRAM_MODEL_TYPE)),		@PP_ARCUSFIL_PROGRAM_MODEL_YEAR,
				--LTRIM(RTRIM(@PP_ARCUSFIL_PROGRAM_MODEL_MAKER)),
				-- ===========================
				@PP_K_USUARIO_ACCION, GETDATE(), @PP_K_USUARIO_ACCION, GETDATE(),
				0, NULL, NULL  )	
	-- //////////////////////////////////////////////////////////////
GO

---- ===================================================================================================================
SET NOCOUNT OFF
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 1, 'WD7', '2021 WL DL 75 VPD'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 2, '77H', 'U377 FORD HEADREST'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 3, 'WDK', '2021 WK WD 2ND ROW ARMREST'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 4, 'WLE', '2021 WL EISMANN'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 5, 'C3A', '2021 WS BL-GL EEP 3RD ROW'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 5, 'C3B', '2021 WS AL JEEP 3RD ROW'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 5, 'FW2', '2021 WS JEEP SL NEVER QUILTED'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 5, 'FWS', '2021 WS AL JEEP BASE'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 5, 'S3S', '2021 WS SL JEEP 3RD ROW'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 5, 'S3U', '2021 WS UL JEEP 3RD ROW'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 5, 'WS3', '2021 WS UL ALWAYS QUILTED'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 6, 'MCY', 'U364 MERCURY LTD FINDALY'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 7, 'GAR', 'U388 LINCOLN ARMREST'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 8, 'GR1', '2021 WL 75 QUADS 2ND. ROW ARMR'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 8, 'GRM', '2021 WL 74/75 2ND. ROW ARMREST'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 8, 'GW2', '2021 WL 75 QUADS 2ND. ROW AR'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 8, 'GWL', '2021 WL 74/75 2ND. ROW ARMRE'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 9, 'GR2', 'WS FOLDING 2ND-ROW ARM REST'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 9, 'GWS', '2021 WS GRAN WAGONNER'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 10, '193', 'GMT 193 2007'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 10, 'GM1', 'GMT 191 PONTIAC TORRENT'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 10, 'GM2', 'GMT 192 PONTIAC PERSUIT'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 10, 'GM3', 'ARMREST GMT 193'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 10, 'GXP', 'GMT 192 GXP 2008'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 11, 'JLI', '2018 JEEP JL'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 11, 'JPH', '2020 JEEP JL PHEV'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 11, 'JPS', '2021 JEEP JL PHEV SUMMIT'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 11, 'JSU', 'JEEPJL SUMMIT'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 12, 'JJT', '2019 JEEP JT'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 12, 'JTM', '2019 JEEP JT MOJAVE'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 12, 'JTS', '2021 JEEP JT SUMMIT'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 13, '87C', 'U387 FORD CUTTING EDGE'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 13, '87P', 'U387 FORD PREMIUM'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 14, '88A', 'U388 LINCOLN ARMREST'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 14, '88H', 'U388 HEADREST'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 14, '88L', 'U388 LINCOLN LIMITED'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 15, 'VFL', 'V229 FORD FREESTAR LTD'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 15, 'VML', 'V229 FREESTAR MERCURY LTD'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 15, 'VMP', 'V229 FREESTAR MPA'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 15, 'VMX', 'V229 FREESTAR MXA'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 16, 'WLS', 'WLS JEEP 2020'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 17, '191', 'GMT 191 2008'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 17, '192', 'GMT 192 2008'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 17, 'ARM', 'ARMREST GMT 193'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 17, 'G93', 'GMT 193 2008'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 17, 'GX2', 'GMT 192 GXP 2008'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 18, 'PL0', 'U388 CONSOLE'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 19, 'CHI', 'GM360 CHEVY / ISUZU /GMC CHINA'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 20, '114', 'EN114 CONSOLE JCI'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 20, 'JCT', 'JCI-TESLA'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 21, 'BUI', 'GM 360 BUICK'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 21, 'CHE', 'GM 360 CHEVY / ISUZU / GMC'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 21, 'DEN', 'GM 360 DENALY'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 21, 'GSS', 'GM 360 TRAILBLAZER SS'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 21, 'SAA', 'GM 360 SAAB'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 22, '415', 'P415 PLATINIUM'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 23, '228', 'U228 NAVIGATOR LUX/ULT'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 23, 'NAV', 'U228 NAVIGATOR LUX EDIASA 3'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 24, 'SHA', 'GM 360 CHEVY/ISUZU/GMC SHANGAI'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 24, 'SHI', 'GM360 CHEVY SHANGAI'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 25, 'KHE', 'U388 HEADREST'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 26, 'THL', '2013 D258 TAURUS LTD'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 26, 'THO', '2013 D258 TAURUS SHO & LIMITED'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 26, 'TSL', '2013 D258 TAURUS SEL'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 27, '365', 'GMX 365 2008 FIXED'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 27, 'G65', 'GMX365 BUICK LACROSSE'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 28, 'CAL', '2013 S197 MUSTANG CALIFORNIA'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 28, 'IUP', '2013 S197 MUSTANG IUP'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 28, 'PRM', '2013 S197 MUSTANG PREMIUM'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 28, 'SH1', '2013 S197 MUSTANG SHELBY 5B8'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 28, 'SH2', '2013 S197 MUSTANG SHELBY TT'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 29, 'GMC', 'GMX 001 COUPE'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 29, 'GX1', 'GMX 001 COUPE L4'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 29, 'GXS', 'GMX001 SEDAN'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 30, 'U20', 'U204 MAZDA AIR BAG'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 30, 'U2F', 'U204 FORD LTD AB'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 30, 'U2L', 'U204 FORD LTD STD'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 30, 'U2M', 'U204 MAZDA PREMIUM'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 31, 'U3L', 'U364 MERCURY LTD STD'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 31, 'U3P', 'U364 MCY PREMIUM'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 32, 'HRM', 'U377 HEADREST 2010'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 32, 'MAZ', 'U377 MAZDA PREMIUM 2009'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 32, 'MP9', 'U377 MERCURY PREMIUM 2009'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 32, 'PL1', 'U377 FORD PREMIUM 11 PLM'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 32, 'U37', 'U377 MERCURY LTD 2008'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 32, 'U3M', 'U377 MERCURY PREMIUM 2008'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 32, 'U77', 'U377 FORD MONO TONE'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 32, 'UMA', 'U377 MAZDA PREMIUM 2008'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 33, 'U55', '2019 U553 EXPEDITION'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 34, 'PLA', 'VN-127 FORD ECONOLINE'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 35, 'W7A', '2021 WL 74 AL'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 35, 'W7B', '2021 WL 74 BL'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 35, 'W7C', '2021 WL 74 CL 8W'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 35, 'W7D', '2021 WL 74 DL'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 35, 'W7E', '2021 WL 74 EC'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 35, 'W7S', '2021 WL 74 SL'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 35, 'W7T', '2021 WL 74 TL'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 35, 'WAL', '2021 WL 75 AL 8W LIMITED'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 35, 'WC1', '2021 WL 75 CL 12 WAY'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 35, 'WCL', '2021 WL 75 CL 8 WAY'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 35, 'WDL', '2021 WL 75 DL LIMITED'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 35, 'WEC', '2021 WL 75 EC SUMMIT'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 35, 'WLB', '2021 WL 75 BL OVERLAND'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 35, 'WLK', '2021 WL KL 8W BASE SRT'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 35, 'WTL', '2021 WL 75 TL 12 WAY'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 36, 'PL4', 'D471 SEL 2012'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 36, 'PL5', 'D471 LTD 2012'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 36, 'PLC', 'D471 LTD PLATINIUM'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 36, 'PLD', 'D471 SEL 2013'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 36, 'PLE', 'D471 LTD 2013'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 36, 'PLS', 'D471 2016 SALERNO'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 37, '3SU', 'GMT 315 SUV'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 38, 'RDL', '2021 RU DL PINNACLE'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 38, 'RUA', '2016 RU OPCION AL'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 38, 'RUE', '2016 RU OPCION EL'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 38, 'RUM', '2016 RU OPCION ML'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 39, '387', 'U387 FORD PREMIUM'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 39, 'FCE', 'U387 FORD CUTTING EDGE'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 39, 'GRE', 'U387 FORD GREY'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 39, 'PL2', 'U387 FORD SEL 2011 PLM'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 39, 'PL7', 'U387 FORD SEL 2012'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 39, 'PL8', 'U387 FORD SPORT 2012'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 39, 'PL9', 'U387 FORD SPORT 2011'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 39, 'PVP', 'U387 FORD VPP'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 39, 'SL3', '2013 U387 SEL'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 40, 'L88', 'U388 LINCOLN LIMITED'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 40, 'PL3', 'U388 LINCOLN BASE 2012'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 40, 'PL6', 'U388 LINCOLN ULTIMATE'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 40, 'PLB', 'U388 HEADREST 2012'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 41, 'U54', 'U540 VINYL LAMINATION'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 42, 'WD2', '2017 WD ML DOS TONOS'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 42, 'WDM', '2017 WD ML'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 42, 'WPL', '2018 WD PL'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 43, 'WBL', '2017 WK BL'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 43, 'WEL', '2017 WK-EL RESERVE'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 43, 'WKG', '2014 WK JEEP GL/DL'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 43, 'WKJ', '2017 WK CJ'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 43, 'WKL', '2015 WK KL ALTITUDE II'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 43, 'WKT', '2014 WK JEEP GL/DL TWO TONES'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 43, 'WKU', '2014 WK JEEP UL'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 43, 'WKY', '2018 WK YL'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 43, 'WKZ', '2014 WK DZ(SRT)'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 43, 'WNL', '2018 WK NL'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 43, 'SI3', '3NEWMODELSIS'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 43, 'XYZ', 'WK TEST'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 44, 'WSL', '2019 WS JEEP AL'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 45, 'MYS', 'U388 HEADREST'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 46, 'THE', 'U228 NAVIGATOR HEADREST'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 47, 'RUP', '2021 RU PINNACLE'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 48, 'WPI', '2021 WPI WD CONSOLE LID'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 49, 'YWD', 'WS YANGFENG DOOR PANEL'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 49, 'YWS', '2021 WS JEEP GRAND WAGONEER'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 50, 'YC4', '2021 WL 74 JEEP GRAND CHEROKEE'
EXECUTE [dbo].[PG_CI_ARCUSFIL_PROGRAM_MODEL]  0, 0, 50, 'YC5', '2021 WL 75 JEEP GRAND CHEROKEE'

SET NOCOUNT ON
GO

--UPDATE	ARCUSFIL_PROGRAM_MODEL
--SET		D_ARCUSFIL_PROGRAM_MODEL=''
--WHERE	D_ARCUSFIL_PROGRAM_MODEL like '%--%'

--UPDATE	ARCUSFIL_PROGRAM_MODEL
--SET		ARCUSFIL_PROGRAM_MODEL_MODEL=''
--WHERE	ARCUSFIL_PROGRAM_MODEL_MODEL like '%--%'

--UPDATE	ARCUSFIL_PROGRAM_MODEL
--SET		ARCUSFIL_PROGRAM_MODEL_YEAR=''
--WHERE	ARCUSFIL_PROGRAM_MODEL_YEAR like '%--%'

--UPDATE	ARCUSFIL_PROGRAM_MODEL
--SET		ARCUSFIL_PROGRAM_MODEL_MAKER=''
--WHERE	ARCUSFIL_PROGRAM_MODEL_MAKER like '%--%'