-- //////////////////////////////////////////////////////////////
-- // DATA BASE:		DATA_02
-- // MODULE:			APQP_MODEL
-- // OPERATION:		TABLA
-- //////////////////////////////////////////////////////////////
-- // AUTHOR:			AX
-- // CREATION DATE:	20210122
-- ////////////////////////////////////////////////////////////// 

USE [DATA_02Pruebas]
GO

-- //////////////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////////////
-- // DROPs
-- //////////////////////////////////////////////////////////////
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[APQP_MODEL_DET]') AND type in (N'U'))
	DROP TABLE [dbo].[APQP_MODEL_DET]
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[APQP_MODEL_HDR]') AND type in (N'U'))
	DROP TABLE [dbo].[APQP_MODEL_HDR]
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[APQP_MODEL_ACTIVITY_LIST]') AND type in (N'U'))
	DROP TABLE [dbo].[APQP_MODEL_ACTIVITY_LIST]
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[APQP_MODEL_HDR_TYPE]') AND type in (N'U'))
	DROP TABLE [dbo].[APQP_MODEL_HDR_TYPE]
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[STATUS_APQP_MODEL]') AND type in (N'U'))
	DROP TABLE [dbo].[STATUS_APQP_MODEL]
GO


-- ////////////////////////////////////////////////////////////////
-- //					STATUS_APQP_MODEL				 
-- ////////////////////////////////////////////////////////////////

CREATE TABLE [dbo].[STATUS_APQP_MODEL] (
	[K_STATUS_APQP_MODEL]				[INT]			NOT NULL,
	[D_STATUS_APQP_MODEL]				[VARCHAR](100)	NOT NULL,
	[C_STATUS_APQP_MODEL]				[VARCHAR](255)	NOT NULL,
	[S_STATUS_APQP_MODEL]				[VARCHAR](10)	NOT NULL,
	[O_STATUS_APQP_MODEL]				[INT]			NOT NULL,
	[L_STATUS_APQP_MODEL]				[INT]			NOT NULL,
	[K_STATUS_APQP_MODEL_CLASS]			[INT]			NOT NULL
) ON [PRIMARY]
GO
-- //////////////////////////////////////////////////////
ALTER TABLE [dbo].[STATUS_APQP_MODEL]
	ADD CONSTRAINT [PK_STATUS_APQP_MODEL]
		PRIMARY KEY CLUSTERED ([K_STATUS_APQP_MODEL])
GO
CREATE UNIQUE NONCLUSTERED 
	INDEX [UN_STATUS_APQP_MODEL_01_DESCRIPCION] 
	   ON [dbo].[STATUS_APQP_MODEL] ( [D_STATUS_APQP_MODEL] )
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_CI_STATUS_APQP_MODEL]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_CI_STATUS_APQP_MODEL]
GO
-- //////////////////////////////////////////////////////////////
-- //				CI - STATUS_APQP_MODEL
-- //////////////////////////////////////////////////////////////
CREATE PROCEDURE [dbo].[PG_CI_STATUS_APQP_MODEL]
	@PP_K_SISTEMA_EXE					INT,
	@PP_K_USUARIO_ACCION				INT,
	-- ===========================
	@PP_K_STATUS_APQP_MODEL			INT,
	@PP_D_STATUS_APQP_MODEL			VARCHAR(100),
	@PP_C_STATUS_APQP_MODEL			VARCHAR(255),
	@PP_S_STATUS_APQP_MODEL			VARCHAR(10),
	@PP_O_STATUS_APQP_MODEL			INT,
	@PP_L_STATUS_APQP_MODEL			INT,
	@PP_K_STATUS_APQP_MODEL_CLASS	INT
AS
	-- ===========================
	INSERT INTO STATUS_APQP_MODEL
			(	[K_STATUS_APQP_MODEL], [D_STATUS_APQP_MODEL], 
				[C_STATUS_APQP_MODEL], [S_STATUS_APQP_MODEL], 
				[O_STATUS_APQP_MODEL], [L_STATUS_APQP_MODEL],
				[K_STATUS_APQP_MODEL_CLASS]		)
	VALUES	
			(	@PP_K_STATUS_APQP_MODEL, @PP_D_STATUS_APQP_MODEL, 
				@PP_C_STATUS_APQP_MODEL, @PP_S_STATUS_APQP_MODEL,
				@PP_O_STATUS_APQP_MODEL, @PP_L_STATUS_APQP_MODEL,
				@PP_K_STATUS_APQP_MODEL_CLASS	)		
	-- //////////////////////////////////////////////////////////////
GO
SET NOCOUNT ON
--	K_STATUS_APQP_MODEL_CLASS		PARA EL ENCABEZADO ES CLASE 10		/	PARA LAS ACTIVIDADES ES CLASE 20
-- ============================================================================================================
--	ESTATUS PARA EL CIERRE EL ENCABEZADO DE APQP_MODEL
EXECUTE [dbo].[PG_CI_STATUS_APQP_MODEL]  0, 139,	00, '( POR DEFINIR )'		,'' , 'XDEFI'	, 00 , 1	,00
EXECUTE [dbo].[PG_CI_STATUS_APQP_MODEL]  0, 139,	01, 'ACTIVA'				,'' , 'ACTIV'	, 10 , 1	,10
EXECUTE [dbo].[PG_CI_STATUS_APQP_MODEL]  0, 139,	02, 'INACTIVA'				,'' , 'INACT'	, 20 , 1	,10
-- ============================================================================================================
--	ESTATUS PARA EL CIERRE DE LAS ACTIVIDADES
EXECUTE [dbo].[PG_CI_STATUS_APQP_MODEL]  0, 139,	10, 'ABIERTA'				,'' , 'ABIER'	, 10 , 1	,20
EXECUTE [dbo].[PG_CI_STATUS_APQP_MODEL]  0, 139,	11, 'CERRADA'				,'' , 'CERRA'	, 20 , 1	,20
SET NOCOUNT OFF
GO


-- ////////////////////////////////////////////////////////////////
-- //					APQP_MODEL_HDR_TYPE				 
-- ////////////////////////////////////////////////////////////////

CREATE TABLE [dbo].[APQP_MODEL_HDR_TYPE] (
	[K_APQP_MODEL_HDR_TYPE]				[INT]			NOT NULL,
	[D_APQP_MODEL_HDR_TYPE]				[VARCHAR](100)	NOT NULL,
	[C_APQP_MODEL_HDR_TYPE]				[VARCHAR](255)	NOT NULL,
	[S_APQP_MODEL_HDR_TYPE]				[VARCHAR](10)	NOT NULL,
	[O_APQP_MODEL_HDR_TYPE]				[INT]			NOT NULL,
	[L_APQP_MODEL_HDR_TYPE]				[INT]			NOT NULL
) ON [PRIMARY]
GO
-- //////////////////////////////////////////////////////
ALTER TABLE [dbo].[APQP_MODEL_HDR_TYPE]
	ADD CONSTRAINT [PK_APQP_MODEL_HDR_TYPE]
		PRIMARY KEY CLUSTERED ([K_APQP_MODEL_HDR_TYPE])
GO
CREATE UNIQUE NONCLUSTERED 
	INDEX [UN_APQP_MODEL_HDR_TYPE_01_DESCRIPCION] 
	   ON [dbo].[APQP_MODEL_HDR_TYPE] ( [D_APQP_MODEL_HDR_TYPE] )
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_CI_APQP_MODEL_HDR_TYPE]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_CI_APQP_MODEL_HDR_TYPE]
GO
-- //////////////////////////////////////////////////////////////
-- //				CI - APQP_MODEL_HDR_TYPE
-- //////////////////////////////////////////////////////////////
CREATE PROCEDURE [dbo].[PG_CI_APQP_MODEL_HDR_TYPE]
	@PP_K_SISTEMA_EXE					INT,
	@PP_K_USUARIO_ACCION				INT,
	-- ===========================
	@PP_K_APQP_MODEL_HDR_TYPE			INT,
	@PP_D_APQP_MODEL_HDR_TYPE			VARCHAR(100),
	@PP_C_APQP_MODEL_HDR_TYPE			VARCHAR(255),
	@PP_S_APQP_MODEL_HDR_TYPE			VARCHAR(10),
	@PP_O_APQP_MODEL_HDR_TYPE			INT,
	@PP_L_APQP_MODEL_HDR_TYPE			INT
AS
	-- ===========================
	INSERT INTO APQP_MODEL_HDR_TYPE
			(	[K_APQP_MODEL_HDR_TYPE], [D_APQP_MODEL_HDR_TYPE], 
				[C_APQP_MODEL_HDR_TYPE], [S_APQP_MODEL_HDR_TYPE], 
				[O_APQP_MODEL_HDR_TYPE], [L_APQP_MODEL_HDR_TYPE]		)
	VALUES	
			(	@PP_K_APQP_MODEL_HDR_TYPE, @PP_D_APQP_MODEL_HDR_TYPE, 
				@PP_C_APQP_MODEL_HDR_TYPE, @PP_S_APQP_MODEL_HDR_TYPE,
				@PP_O_APQP_MODEL_HDR_TYPE, @PP_L_APQP_MODEL_HDR_TYPE	)		
	-- //////////////////////////////////////////////////////////////
GO
SET NOCOUNT ON
--EXECUTE [dbo].[PG_CI_APQP_MODEL_HDR_TYPE]  0, 139,	00, '( TO DEFINE )'			,'' , '2DFINE'	, 00 , 1
EXECUTE [dbo].[PG_CI_APQP_MODEL_HDR_TYPE]  0, 139,	01, 'NUEVO MODELO'				,'' , 'NVOMOD'	, 10 , 1
EXECUTE [dbo].[PG_CI_APQP_MODEL_HDR_TYPE]  0, 139,	02, 'CAMBIO INGENIERÍA'			,'' , 'CMBING'	, 20 , 1
SET NOCOUNT OFF
GO


-- ////////////////////////////////////////////////////////////////
-- //					APQP_MODEL_ACTIVITY_LIST
-- ////////////////////////////////////////////////////////////////
CREATE TABLE [dbo].[APQP_MODEL_ACTIVITY_LIST]	(
			-- ============================	
			[K_APQP_MODEL_ACTIVITY_LIST]				[INT] IDENTITY (1,1)	NOT NULL,
			[D_APQP_MODEL_ACTIVITY_LIST]				[VARCHAR](255),
			[RESPONSIBLE_APQP_MODEL_ACTIVITY_LIST]		[VARCHAR](255)	NOT NULL,
			-- ===========================
			[L_APQP_MODEL_TYPE_01]						[INT] NOT NULL DEFAULT 1,	-- TYPE	= NEW MODEL
			[L_APQP_MODEL_TYPE_02]						[INT] NOT NULL DEFAULT 0,
			[L_APQP_MODEL_TYPE_03]						[INT] NOT NULL DEFAULT 0,
			[L_APQP_MODEL_TYPE_04]						[INT] NOT NULL DEFAULT 0,
			-- ===========================
) ON [PRIMARY]
GO
-- //////////////////////////////////////////////////////
ALTER TABLE [dbo].[APQP_MODEL_ACTIVITY_LIST]	
	ADD CONSTRAINT [K_APQP_MODEL_ACTIVITY_LIST]
		PRIMARY KEY CLUSTERED ([K_APQP_MODEL_ACTIVITY_LIST])
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_CI_APQP_MODEL_ACTIVITY_LIST]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_CI_APQP_MODEL_ACTIVITY_LIST]
GO
-- //////////////////////////////////////////////////////////////
-- //				CI - APQP_MODEL_ACTIVITY_LIST
-- //////////////////////////////////////////////////////////////
CREATE PROCEDURE [dbo].[PG_CI_APQP_MODEL_ACTIVITY_LIST]
	@PP_K_SISTEMA_EXE					INT,
	@PP_K_USUARIO_ACCION				INT,
	-- ===========================
	--@PP_K_APQP_MODEL_ACTIVITY_LIST				INT,
	-- ===========================
	@PP_L_APQP_MODEL_ACTIVITY_LIST_01			INT,
	@PP_L_APQP_MODEL_ACTIVITY_LIST_02			INT,
	@PP_L_APQP_MODEL_ACTIVITY_LIST_03			INT,
	@PP_L_APQP_MODEL_ACTIVITY_LIST_04			INT,
	@PP_RESPONSIBLE_APQP_MODEL_ACTIVITY_LIST	VARCHAR(255),
	@PP_D_APQP_MODEL_ACTIVITY_LIST				VARCHAR(255)
AS
	-- ===========================
	INSERT INTO APQP_MODEL_ACTIVITY_LIST
			(	--	[K_APQP_MODEL_ACTIVITY_LIST],	
				[D_APQP_MODEL_ACTIVITY_LIST], 
				[RESPONSIBLE_APQP_MODEL_ACTIVITY_LIST],
				[L_APQP_MODEL_TYPE_01],			[L_APQP_MODEL_TYPE_02],
				[L_APQP_MODEL_TYPE_03],			[L_APQP_MODEL_TYPE_04]			)
	VALUES	
			(	--	@PP_K_APQP_MODEL_ACTIVITY_LIST, 
				@PP_D_APQP_MODEL_ACTIVITY_LIST,
				@PP_RESPONSIBLE_APQP_MODEL_ACTIVITY_LIST,
				@PP_L_APQP_MODEL_ACTIVITY_LIST_01,	@PP_L_APQP_MODEL_ACTIVITY_LIST_02,
				@PP_L_APQP_MODEL_ACTIVITY_LIST_03,	@PP_L_APQP_MODEL_ACTIVITY_LIST_04			)		
	-- //////////////////////////////////////////////////////////////
GO
SET NOCOUNT ON
EXECUTE [dbo].[PG_CI_APQP_MODEL_ACTIVITY_LIST]  0, 139,	1,0,0,0,	'OMAR D.'										,'FECHA DE AVISO DEL CAMBIO O INICIO'
EXECUTE [dbo].[PG_CI_APQP_MODEL_ACTIVITY_LIST]  0, 139,	1,0,0,0,	'JORGE H, OMAR D.'								,'INICIO DEL PROGRAMA O CAMBIO (IMPLEMENTACION)'
EXECUTE [dbo].[PG_CI_APQP_MODEL_ACTIVITY_LIST]  0, 139,	1,0,0,0,	'OMAR D. BILL REID'								,'COTIZACIÓN'
EXECUTE [dbo].[PG_CI_APQP_MODEL_ACTIVITY_LIST]  0, 139,	1,0,0,0,	'GUILLERMO M, JORGE H.'							,'CAPACIDAD Y FACTIBILIDAD DE CORTE (EVALUACION DE REQUERIMIENTOS DE VOLUMEN Y DE ENTREGA)'
EXECUTE [dbo].[PG_CI_APQP_MODEL_ACTIVITY_LIST]  0, 139,	1,0,0,0,	'OMAR D. MIGUEL C.'								,'DIBUJOS, PLANOS O MYLARS O ESPECIFICACIONES DE INGENIERIA NUEVAS (VER ACTIVIDAD #22)'
EXECUTE [dbo].[PG_CI_APQP_MODEL_ACTIVITY_LIST]  0, 139,	1,0,0,0,	'GUILLERMO M, OMAR D.'							,'COTIZACIÓN Y COMPRA DE HERRAMENTAL DE CORTE'
EXECUTE [dbo].[PG_CI_APQP_MODEL_ACTIVITY_LIST]  0, 139,	1,0,0,0,	'OMAR D, GUILLERMO M.'							,'DISPONIBILIDAD DE MATERIA PRIMA, CANTIDADES Y COLORES'
EXECUTE [dbo].[PG_CI_APQP_MODEL_ACTIVITY_LIST]  0, 139,	1,0,0,0,	'PATRICIA CH, JORGE H, GUILLERMO M.'			,'REQUERIMIENTOS DE MANO DE OBRA ADICIONAL'
EXECUTE [dbo].[PG_CI_APQP_MODEL_ACTIVITY_LIST]  0, 139,	1,0,0,0,	'GUILLERMO M, JORGE H.'							,'NECESIDES DE EQUIPO ADICIONAL O DE MEJORAS AL YA EXISTENTE'
EXECUTE [dbo].[PG_CI_APQP_MODEL_ACTIVITY_LIST]  0, 139,	1,0,0,0,	'PATRICIA CHAVEZ, JORGE H, GUILLERMO M.'		,'NECESIDADES DE ENTRENAMIENTO ADICIONALES'
EXECUTE [dbo].[PG_CI_APQP_MODEL_ACTIVITY_LIST]  0, 139,	1,0,0,0,	'MIGUEL C, CARLOS ZAMORA.'						,'DOCUMENTACIÓN DE CALIDAD, CONTROL PLAN, FMEA´S, DIAGRAMA DE FLUJO, ETC.(PPAP)'
EXECUTE [dbo].[PG_CI_APQP_MODEL_ACTIVITY_LIST]  0, 139,	1,0,0,0,	'MIGUEL C, GUILLERMO M.'						,'EQUIPO DE INSPECCIÓN ADICIONAL, DISPONIBILIDAD DE CRITERIOS DE CALIDAD, MASTERS, AYUDAS VISUALES, ETC.'
EXECUTE [dbo].[PG_CI_APQP_MODEL_ACTIVITY_LIST]  0, 139,	1,0,0,0,	'GUILLERMO M, MIGUEL C.'						,'DOCUMENTACIÓN DE PISO, INSTR DE TRAB. Y CRITERIOS'
EXECUTE [dbo].[PG_CI_APQP_MODEL_ACTIVITY_LIST]  0, 139,	1,0,0,0,	'MIGUEL C, OMAR D.'								,'REQUERIMIENTOS DE MONITOREO, INSPECCIÓN Y MEDICION DEL PRODUCTO O DEL PROCESO.'
EXECUTE [dbo].[PG_CI_APQP_MODEL_ACTIVITY_LIST]  0, 139,	1,0,0,0,	'MIGUEL C, OMAR D.'								,'ESPECIFICACIONES ADICIONALES O ESPECIALES DE INGENIERIA, ESTO INCLUYE CARACTERISTICAS CRITICAS'
EXECUTE [dbo].[PG_CI_APQP_MODEL_ACTIVITY_LIST]  0, 139,	1,0,0,0,	'MIGUEL C, OMAR D.'								,'CARACTERISTICAS ESPECIALES DEL CLIENTE (MANUAL DE PROVEEDORES)'
EXECUTE [dbo].[PG_CI_APQP_MODEL_ACTIVITY_LIST]  0, 139,	1,0,0,0,	'GUILLERMO M, MIGUEL C.'						,'ARCHIVOS DE CORTE'
EXECUTE [dbo].[PG_CI_APQP_MODEL_ACTIVITY_LIST]  0, 139,	1,0,0,0,	'MIGUEL C, OMAR D.'								,'VALIDACIONES DE ACCIONES/MUESTRAS EN AREAS MODELO ANTES DE IMPLEMENTAR MASIVAMENTE'
EXECUTE [dbo].[PG_CI_APQP_MODEL_ACTIVITY_LIST]  0, 139,	1,0,0,0,	'MIGUEL C, OMAR D.'								,'MASTERS DE COLOR, MANUAL DE MARCAS NATURALES Y/O CUALQUIER OTRO CRITERIO DE CALIDAD QUE SE REQUIERA'
EXECUTE [dbo].[PG_CI_APQP_MODEL_ACTIVITY_LIST]  0, 139,	1,0,0,0,	'OMAR D.'										,'NO. DE PARTE EN EL SISTEMA'
EXECUTE [dbo].[PG_CI_APQP_MODEL_ACTIVITY_LIST]  0, 139,	1,0,0,0,	'MIGUEL C, GUILLERMO M'							,'INFORMACIÓN DE EMPAQUE Y ETIQUETAS'
EXECUTE [dbo].[PG_CI_APQP_MODEL_ACTIVITY_LIST]  0, 139,	1,0,0,0,	'GUILLERMO M.'									,'INVENTARIOS (OBSOLESCENCIAS)'
EXECUTE [dbo].[PG_CI_APQP_MODEL_ACTIVITY_LIST]  0, 139,	1,0,0,0,	'OMAR D.'										,'RECORDATORIO DE REQUERIMIENTO DE CONFIDENCIALIDAD DE IATF 16949'
EXECUTE [dbo].[PG_CI_APQP_MODEL_ACTIVITY_LIST]  0, 139,	1,0,0,0,	'TODO EL EQUIPO'								,'CONSIDERACIONES PREVENTIVAS DEL PRODUCTO O DEL PROCESO.'
EXECUTE [dbo].[PG_CI_APQP_MODEL_ACTIVITY_LIST]  0, 139,	1,0,0,0,	'OMAR D.'										,'OBJETIVOS DE CALIDAD'
EXECUTE [dbo].[PG_CI_APQP_MODEL_ACTIVITY_LIST]  0, 139,	1,0,0,0,	'TODO EL EQUIPO'								,'CONSIDERACIONES DE INFRAESTRUCUTRAS Y MEDIO AMBIENTE DE TRABAJO'
EXECUTE [dbo].[PG_CI_APQP_MODEL_ACTIVITY_LIST]  0, 139,	1,0,0,0,	'TODO EL EQUIPO'								,'CONSIDERACIONES DE SEGURIDAD'
EXECUTE [dbo].[PG_CI_APQP_MODEL_ACTIVITY_LIST]  0, 139,	1,0,0,0,	'GERENCIA GENERAL'								,'OBJETIVO DE PRODUCTIVIDAD '
EXECUTE [dbo].[PG_CI_APQP_MODEL_ACTIVITY_LIST]  0, 139,	1,0,0,0,	'OMAR DECENA'									,'LECCIONES APRENDIDAS DE PROCESOS/PRODUCTOS SIMILARES'
SET NOCOUNT OFF
GO

-- ////////////////////////////////////////////////////////////////
-- //					APQP_MODEL_HDR				 
-- ////////////////////////////////////////////////////////////////
CREATE TABLE [dbo].[APQP_MODEL_HDR]	(
			-- ============================	
			[K_APQP_MODEL_HDR]					[INT] IDENTITY (1,1)	NOT NULL,
			[D_APQP_MODEL_HDR]					[VARCHAR](255),
			[C_APQP_MODEL_HDR]					[VARCHAR](500)	NOT NULL,
			-- ===========================
			--[APQP_MODEL_HDR_OPTION_01]			[VARCHAR](255),						---	OPTIONS
			--[APQP_MODEL_HDR_OPTION_02]			[VARCHAR](255),						---	OPTIONS
			-- ===========================
			[K_ARCUSFIL]						[INT] NOT NULL,
			[K_ARCUSFIL_PROGRAM]				[INT] NOT NULL,
			--	[S_APQP_MODEL_HDR]					[VARCHAR](25),						---	PROGRAM
			-- ===========================
			[K_STATUS_APQP_MODEL]				[INT] NOT NULL DEFAULT 1,
			[K_APQP_MODEL_HDR_TYPE]				[INT] NOT NULL DEFAULT 1,
			-- ===========================
			[APQP_MODEL_HDR_NUMBER]				[VARCHAR](255),
			[F_APQP_MODEL_HDR_CREATED]			[DATE]	NOT NULL,
			-- ===========================
			[APQP_ECN_RFQ_SP_REFERENCE]			[VARCHAR](255)	NOT NULL DEFAULT ''
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[APQP_MODEL_HDR]
ADD
			[K_USUARIO_ALTA]					[INT] NOT NULL,
			[F_ALTA]							[DATETIME] NOT NULL,
			[K_USUARIO_CAMBIO]					[INT] NOT NULL,
			[F_CAMBIO]							[DATETIME] NOT NULL,
			[L_BORRADO]							[INT] NOT NULL,
			[K_USUARIO_BAJA]					[INT] NULL,
			[F_BAJA]							[DATETIME] NULL;
GO

-- //////////////////////////////////////////////////////
ALTER TABLE [dbo].[APQP_MODEL_HDR]	
	ADD CONSTRAINT [K_APQP_MODEL_HDR]
		PRIMARY KEY CLUSTERED ([K_APQP_MODEL_HDR])
GO


-- ////////////////////////////////////////////////////////////////
-- //					APQP_MODEL_DET
-- ////////////////////////////////////////////////////////////////
CREATE TABLE [dbo].[APQP_MODEL_DET]	(
			-- ============================	
			[K_APQP_MODEL_DET]					[INT] IDENTITY (1,1)	NOT NULL,
			[K_APQP_MODEL_HDR]					[INT] NOT NULL DEFAULT 0,
			[K_APQP_MODEL_ACTIVITY_LIST]		[INT] NOT NULL DEFAULT 0,
			-- ===========================
			[F_APQP_MODEL_DET_CREATED]			[DATE]	NOT NULL DEFAULT GETDATE(),
			[F_APQP_MODEL_DET_COMPLETED]		[DATE]	NULL,
			-- ===========================
			[K_STATUS_APQP_MODEL]				[INT] NOT NULL DEFAULT 1,
			-- ===========================
			[L_APQP_MODEL_DET_COMPLETED]		[INT] NOT NULL DEFAULT 0
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[APQP_MODEL_DET]
ADD
			[K_USUARIO_ALTA]					[INT] NOT NULL,
			[F_ALTA]							[DATETIME] NOT NULL,
			[K_USUARIO_CAMBIO]					[INT] NOT NULL,
			[F_CAMBIO]							[DATETIME] NOT NULL,
			[L_BORRADO]							[INT] NOT NULL,
			[K_USUARIO_BAJA]					[INT] NULL,
			[F_BAJA]							[DATETIME] NULL;
GO

-- //////////////////////////////////////////////////////
ALTER TABLE [dbo].[APQP_MODEL_DET]	
	ADD CONSTRAINT [K_APQP_MODEL_DET]
		PRIMARY KEY CLUSTERED ([K_APQP_MODEL_DET])
GO



-- //////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////